### ISSUE TITLE
Alternating blank screen in 2.1.0

### ISSUE THREAD

**Issue by jvaccaro** [hhannine/superpaper#109]
I recently upgraded to Superpaper 2.1.0 from 2.02. Version 2.0.2 worked perfectly on my 3 monitor Ubuntu 20.4LTS, Gnome 36 desktop correctly changing to a different random wallpaper image every 2 hours. 

Upon upgrading to 2.1.0, every other timed switch to a new wallpaper image yields 3 blank screens. If I wait for the delay time to elapse or force a change with **CTRL-ALT-W** a new set of wallpapers appears.

I downgraded back to 2.0.2 but the problem persisted. I have deleted the profile and re-added it, keeping the _Default_ name for the profile.

My Superpaper photo folder is a Dropbox folder holding 3.7GB of images; a mixture of .webp ,jpg and .png formats.

It sounds like some sort of corruption in whatever index(ing) method 2.1.0 uses and the reversion to 2.0.2 happily continued using the malformed indexing.

Please advise what logs and config files you need to troubleshoot

Thank you in advance

---
John Vaccaro
eMail: jvaccaro at gmail.com

_The race is not always to the swift, nor the battle to the strong -but that's the way to bet._ - Damon Runyon

**Comment by hhannine** [comment]
Please run superpaper in the terminal with the debug option and post your results here. Take care that you see the issue during the debugging.

This seems peculiar since any behavior should not persist between different Superpaper versions. Hopefully I can tell what's going on from the log.

**Comment by hhannine** [comment]
Is this issue still ongoing? If it is, please come reopen this issue, and post the debugging log.
