### ISSUE TITLE
Superpaper failed to launch on KDE

### ISSUE THREAD

**Issue by lelouvincx** [hhannine/superpaper#116]
I am using Kubuntu 21.04. After doing 2-step instruction about installing, I tried to launch but it keeps notifying me: "Launching Superpaper (Failed): could not find the program 'superpaper'". I also open terminal and type "superpaper" but it doesn't seem to start.

I can't understand why my system can't launch so I hope to fix this issue.

Screenshots here: https://imgur.com/a/1zP1HTa

**Desktop (please complete the following information):**
 - OS: Kubuntu 21.04
 - Desktop Environment on Linux: KDE
 - Python3-wxgtk4.0 version: 4.0.7+dfsg-10
 - Superpaper package & version: newest version up to April 22th, 2022.

**Comment by amsteel** [comment]
Have to you try to log-off and log-on or reboot? I think it is the path issue.

**Comment by hhannine** [comment]
Were you able to get Superpaper running? As mentioned above, the install directory might not be in your PATH and because of that your terminal doesn't find the executable.
