### ISSUE TITLE
Won't change wall paper - Ubuntu 22.04 dark mode

### ISSUE THREAD

**Issue by amsteel** [hhannine/superpaper#119]
**Describe the bug**
use the lastest main branch code and applied Python 3.10 hotkey fix. Superpaper starts with no issue. Can choose source and save profile. However it won't change the desktop wall paper.
**To Reproduce**
1. Applied python 3.10 hotkey fix,
2. install wxPython
3. clone the main branch. run pip install .
4.  run superpaer

**Expected behavior**
The wallpaper should be updated

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Desktop Environment on Linux: defaut wayland

Logging / debugging contents:
Input images: None
Input profile: None
Input perspective: None
Input spangroups: None
Input offsets: None
User defined command: None
Debugging: True
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')

(superpaper:426845): Gtk-CRITICAL **: 11:45:49.045: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
WARNING: Horizontal and vertical PPI do not match! hor: 127.74852652259331, ver: 95.9160839160839
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1920, 1080), (1920, 1080), (2560, 1080)], OFF_ARR = [(0, 0), (1920, 0), (3840, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND3')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND0')
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=127.74852652259331, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
load_system: archive_file not found: /home/amsteel/.config/superpaper/display_systems.dat
WARNING: Horizontal and vertical PPI do not match! hor: 127.74852652259331, ver: 95.9160839160839
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1920, 1080), (1920, 1080), (2560, 1080)], OFF_ARR = [(0, 0), (1920, 0), (3840, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND3')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND0')
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=127.74852652259331, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
load_system: archive_file not found: /home/amsteel/.config/superpaper/display_systems.dat
running profile job with profile: p1
['/home/amsteel/hostshare/VMShare/WallPaper/3840x2400 [1041P][6.54GB]/03449_thephone_3840x2400.jpg', '/home/amsteel/hostshare/VMShare/WallPaper/2880x1800 [1232P][4.67GB]/03952_iceland_2880x1800.jpg', '/home/amsteel/hostshare/VMShare/WallPaper/2560x1600 [2800P][6.71GB]/02205_fortjefferson_2560x1600.jpg']
Registering binding:                                 ('control', 'super', 'shift', 'h') for profile: example
Registering binding:                                 ('control', 'super', 'shift', 'g') for profile: example_multi
Registering binding:                                 None for profile: p1
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 127.74852652259331, ver: 95.9160839160839
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1920, 1080), (1920, 1080), (2560, 1080)], OFF_ARR = [(0, 0), (1920, 0), (3840, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND3')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND0')
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=127.74852652259331, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
load_system: archive_file not found: /home/amsteel/.config/superpaper/display_systems.dat

(superpaper:426845): Gtk-WARNING **: 11:45:55.371: Error loading theme icon 'dialog-question' for stock: Icon 'dialog-question' not present in theme candy-icons
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
Canvas size: [6400, 1080]
file:///home/amsteel/.cache/superpaper/temp/p1-a.png
DESKTOP_SESSION is: 'ubuntu'
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
p1
multi
False
None
None
None
None
['/home/amsteel/hostshare/VMShare/WallPaper/2880x1800 [1232P][4.67GB];/home/amsteel/hostshare/VMShare/WallPaper/3840x2400 [1041P][6.54GB]', '/home/amsteel/hostshare/VMShare/WallPaper/3840x2400 [1041P][6.54GB];/home/amsteel/hostshare/VMShare/WallPaper/2880x1800 [1232P][4.67GB]', '/home/amsteel/hostshare/VMShare/WallPaper/2560x1600 [2800P][6.71GB];/home/amsteel/hostshare/VMShare/WallPaper/2880x1800 [1232P][4.67GB]']
Unreg hotkey ('control', 'super', 'w')
Unreg hotkey ('control', 'super', 'shift', 'h')
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'shift', 'g')
Registering binding:                                 ('control', 'super', 'shift', 'h') for profile: example
Registering binding:                                 ('control', 'super', 'shift', 'g') for profile: example_multi
Registering binding:                                 None for profile: p1
onApply profile: saved /home/amsteel/.config/superpaper/profiles/p1.profile
Start profile: p1
Running quick profile job with profile: p1
quickswitch file lookup: ['p1-a.png']
file:///home/amsteel/.cache/superpaper/temp/p1-a.png
Starting timed profile job with profile: p1
DESKTOP_SESSION is: 'ubuntu'
WARNING: Horizontal and vertical PPI do not match! hor: 127.74852652259331, ver: 95.9160839160839
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1920, 1080), (1920, 1080), (2560, 1080)], OFF_ARR = [(0, 0), (1920, 0), (3840, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND3')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND0')
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=127.74852652259331, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
load_system: archive_file not found: /home/amsteel/.config/superpaper/display_systems.dat
running profile job with profile: p1
['/home/amsteel/hostshare/VMShare/WallPaper/2880x1800 [1232P][4.67GB]/03842_bayoffiretasmania_2880x1800.jpg', '/home/amsteel/hostshare/VMShare/WallPaper/3840x2400 [1041P][6.54GB]/03506_norwaycoastline_3840x2400.jpg', '/home/amsteel/hostshare/VMShare/WallPaper/2560x1600 [2800P][6.71GB]/03679_hecetahead_2560x1600.jpg']
Canvas size: [6400, 1080]
file:///home/amsteel/.cache/superpaper/temp/p1-b.png
DESKTOP_SESSION is: 'ubuntu'
Traceback (most recent call last):
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper-2.1.0-py3.10.egg/superpaper/gui.py", line 1019, in onSelect
    self.populate_fields(self.list_of_profiles[item])
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper-2.1.0-py3.10.egg/superpaper/gui.py", line 563, in populate_fields
    profile.next_wallpaper_files(),
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper-2.1.0-py3.10.egg/superpaper/data.py", line 498, in next_wallpaper_files
    return self.file_handler.next_wallpaper_files()
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper-2.1.0-py3.10.egg/superpaper/data.py", line 553, in next_wallpaper_files
    next_image = iterable.__next__()
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper-2.1.0-py3.10.egg/superpaper/data.py", line 584, in __next__
    image = self.files[self.counter]
IndexError: list index out of range
example
single
True
120.0
shuffle
None
control+super+shift+h
['/home;/']
test_save failed.
onApply profile: saved None

(superpaper:426845): Gtk-WARNING **: 11:46:26.000: Error loading theme icon 'media-floppy' for stock: Icon 'media-floppy' not present in theme candy-icons

(superpaper:426845): Gtk-WARNING **: 11:46:26.012: Error loading theme icon 'system-run' for stock: Icon 'system-run' not present in theme candy-icons
example
single
True
120.0
shuffle
None
control+super+shift+h
['/home/amsteel/hostshare/VMShare/WallPaper/5120x3200 [242P][2.57GB]']
Unreg hotkey ('control', 'super', 'w')
Unreg hotkey ('control', 'super', 'shift', 'h')
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'shift', 'g')
Registering binding:                                 ('control', 'super', 'shift', 'h') for profile: example
Registering binding:                                 ('control', 'super', 'shift', 'g') for profile: example_multi
Registering binding:                                 None for profile: p1
example
single
True
120.0
shuffle
None
control+super+shift+h
['/home/amsteel/hostshare/VMShare/WallPaper/5120x3200 [242P][2.57GB]']
Unreg hotkey ('control', 'super', 'w')
Unreg hotkey ('control', 'super', 'shift', 'h')
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'shift', 'g')
Registering binding:                                 ('control', 'super', 'shift', 'h') for profile: example
Registering binding:                                 ('control', 'super', 'shift', 'g') for profile: example_multi
Registering binding:                                 None for profile: p1
onApply profile: saved /home/amsteel/.config/superpaper/profiles/example.profile
Start profile: example
Running quick profile job with profile: example
quickswitch file lookup: []
Old file for quickswitch was not found. []
Starting timed profile job with profile: example
WARNING: Horizontal and vertical PPI do not match! hor: 127.74852652259331, ver: 95.9160839160839
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1920, 1080), (1920, 1080), (2560, 1080)], OFF_ARR = [(0, 0), (1920, 0), (3840, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND3')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND0')
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=127.74852652259331, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND4')
load_system: archive_file not found: /home/amsteel/.config/superpaper/display_systems.dat
running profile job with profile: example
/home/amsteel/hostshare/VMShare/WallPaper/5120x3200 [242P][2.57GB]/03665_luminous_5120x3200.jpg
Canvas size: [6400, 1080]
file:///home/amsteel/.cache/superpaper/temp/example-a.png
DESKTOP_SESSION is: 'ubuntu'
```

```

**Comment by amsteel** [comment]
I think it is because I am using dark mode. So I just add another line in wallpaper_processing.py under the "normal" part:
            subprocess.run(["/usr/bin/gsettings", "set",
                            "org.gnome.desktop.background", "picture-uri-dark",
                            file])

it seems working. Not sure if it is the base solution so did not raise a pr.

**Comment by yatahaze** [comment]
Also having the same issue, and your code let me continue using dark mode.

**Comment by hhannine** [comment]
This is now resolved with [8fb427b](https://github.com/hhannine/superpaper/commit/8fb427b8bcf652cdf2c79dadefca97b2d8f79390)
