### ISSUE TITLE
Does not set wallpaper on Gnome 42 when using dark theme

### ISSUE THREAD

**Issue by TimeLincoln** [hhannine/superpaper#125]
When using the Dark theme in gnome 42, superpaper does not set the wallpapers, only works when gnome is set ot the light theme.

**Comment by TimeLincoln** [comment]
Worked around this by setting picture-uri-dark to the same value as picture-uri in /org/gnome/desktop/background using dconf editor

**Comment by TimeLincoln** [comment]
Set a custom command to update picture-uri-dark but seems like the custom command is only run once, not run each time the wallpaper switches so half the time i have the background color and half the time i have a wallpaper right now.

**Comment by TimeLincoln** [comment]
added the set_command to the multi_profile and that fixed it.

**Comment by Commenter25** [comment]
Duplicate of #119, fixed by #123
