### ISSUE TITLE
cannot open "wallpaper configuration" window

### ISSUE THREAD

**Issue by labatts** [hhannine/superpaper#127]
**Describe the bug**
The program refuses to show on the screen.  I am able to run it only because I have previously set it to start in the tray.  When I attempt to open the wallpaper configuration window, I get the following error message:

```
Traceback` (most recent call last):
  File "/home/shawn/.local/lib/python3.10/site-packages/superpaper/tray.py", line 60, in <lambda>
    menu.Bind(wx.EVT_MENU, lambda event: func(event, *args), id=item.GetId())

  File "/home/shawn/.local/lib/python3.10/site-packages/superpaper/tray.py", line 299, in configure_wallpapers
    config_frame = ConfigFrame(self)

  File "/home/shawn/.local/lib/python3.10/site-packages/superpaper/gui.py", line 31, in __init__
    config_panel = WallpaperSettingsPanel(self, parent_tray_obj)

  File "/home/shawn/.local/lib/python3.10/site-packages/superpaper/gui.py", line 74, in __init__
    self.wpprev_pnl = WallpaperPreviewPanel(self, self.display_sys)

  File "/home/shawn/.local/lib/python3.10/site-packages/superpaper/gui.py", line 1363, in __init__
    self.draw_displays()

  File "/home/shawn/.local/lib/python3.10/site-packages/superpaper/gui.py", line 1381, in draw_displays
    bmp_canv = wx.Bitmap.FromRGBA(self.dtop_canvas_relsz[0], self.dtop_canvas_relsz[1], red=0, green=0, blue=0, alpha=255)

TypeError: Bitmap.FromRGBA(): argument 1 has unexpected type 'float'
```

(Spaces added for clarity).  I read the install on linux page.  I originally had it installed through the opensuse main repository, but I uninstalled that and re-installed with the pip method as described on your page.  It has the same results unfortunately.  

**To Reproduce**
1. Attempt to open superpaper.
2. If, as in my case, you are starting with it minimized to systray, click on wallpaper configuration.

**Expected behavior**
open window

**Desktop (please complete the following information):**
 - OS: Opensuse Tumbleweed
 - Desktop Environment on Linux: plasma 5.25
 - Superpaper package & version: 2.1; installed via opensuse repo as well as pip.

**Comment by labatts** [comment]
I'm using the appimage for now and it is working fine.

**Comment by hhannine** [comment]
Thank you for the report, and especially for confirming that the Appimage works! This is a known issue, which is affecting the pypi version when the OS is using python 3.10+. This is fixed here at Github but not in the latest release. Very good to know that the Appimage indeed does work.
