### ISSUE TITLE
[question] CLI interface for next wallpaper

### ISSUE THREAD

**Issue by fecet** [hhannine/superpaper#129]
As the hotkey setting seems not work with python 3.10, is there any way to control it, or at least change wallpaper, in CLI?

**Comment by hhannine** [comment]
I'm looking to create a new release including fixes for the hotkeys in the near future. In the mean time, one workaround to change the wallpaper could the to just kill and restart superpaper? This loads a new wallpaper for the current profile. Alternatively you can fix the hotkey bug if you know Python, see #102
