### ISSUE TITLE
Add indicator of which file is currently the background image

### ISSUE THREAD

**Issue by Ali-Flt** [hhannine/superpaper#131]
Hi,
I'm trying to use superpaper with pywal so that colors would change with the background. I have set a folder as the superpaper source. Could it be possible for superpaper to somehow tell me which image is currently being shown? This way a script can update pywal.
Thanks for this great app

**Comment by Ali-Flt** [comment]
I think this script does the trick
[https://github.com/hhannine/superpaper/blob/master/example-script/run-after-wp-change.py](https://github.com/hhannine/superpaper/blob/master/example-script/run-after-wp-change.py)

**Comment by Ali-Flt** [comment]
Actually thinking about it more, I think other than the actual image itself, the path of the source image (which the multi-monitor background is created from)  is also needed. Does the `run-after-wp-change` script have that as an argument too? or could it be added? 
The issue is that the final background picture created by superpaper may not be used for other places like the background of a messaging app, rather the original image is desired

**Comment by hhannine** [comment]
Currently the source image(s) is/are not passed through, but I think it could be added quite easily.

**Comment by hhannine** [comment]
This is implemented in 292bb1d464860871ea3326430ddf69624b9e2df4
