### ISSUE TITLE
--command option only works when a desktop environment is set

### ISSUE THREAD

**Issue by Ali-Flt** [hhannine/superpaper#132]
I think this if statement shouldn't be inside the if checking if DE env var is set or not. I'm using i3 and want to use `-c` option but isn't letting me
https://github.com/hhannine/superpaper/blob/8fb427b8bcf652cdf2c79dadefca97b2d8f79390/superpaper/wallpaper_processing.py#L1478

**Comment by hhannine** [comment]
Thanks, you're right. As a workaround you can run superpaper by setting the DESKTOP_SESSION variable to anything:
`DESKTOP_SESSION=i3 superpaper`.

**Comment by hhannine** [comment]
This should be resolved with [ec62fe6](https://github.com/hhannine/superpaper/commit/ec62fe6c94fe100fb9196e7d5361b6d9cb2ad21f)
