### ISSUE TITLE
Put configuration options in user directory

### ISSUE THREAD

**Issue by Justinzobel** [hhannine/superpaper#14]
Patch from Arch: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=superpaper

**Comment by hhannine** [comment]
This is something that has been on my to-do list for a long time but it seems to me that if I move the configurations into the default config directory I will also need to solve how to handle the installation, which I haven't gotten around to figuring out.

Would you mind outlining for me what would be the expected installation procedure for a Python application like this? Should the installation process be setup together with the config dir change?

Secondly, if I throw the configs under XDG_CONFIG_HOME/superpaper, would it be an issue to put the temporary wallpaper images under there as well or should I start using a cache folder elsewhere?

**Comment by Justinzobel** [comment]
I'm no code expert sorry so I can't give advice on that side but config and wallpapers should be separate. I would put the wallpapers in `~/.cache/superpaper/wallpapers`

**Comment by hhannine** [comment]
Thanks for your input. I'll _probably_ solve this in two phases. First I'll start using the proper folders if Superpaper is run as a python script so git clones and maybe the AUR package will behave correctly and the portable release packages will stay as they are for the time being. Once I get installation flows setup the new installable releases will use the correct folders of each platform.

**Comment by hhannine** [comment]
This was resolved with:  12aac36c65
