### ISSUE TITLE
Very high memory usage - increases with each walpaper change Ubuntu 22.04.4

### ISSUE THREAD

**Issue by Rob-00t** [hhannine/superpaper#148]
Using Ubuntu
superpaper use of memory is very high. 
The process use till 2 or 3 GB of memory, depending how many time/walpaper change are executed.
I'd like that superpaper process,  be more efficient, in RAM memory usage.

 OS: Ubuntu 22.04.4 LTS
  Desktop Environment
  Superpaper 2.2.1

**Comment by Rob-00t** [comment]
I have take a workaround making a bash script and run it with crontab every 15 minutes like this:


export WAYLAND_DISPLAY=wayland-0
export GNOME_SETUP_DISPLAY=:1
export DISPLAY=:0
kill $(pgrep -f 'superpaper')
/usr/bin/python3 -m superpaper 

Apologise for my poor skill in scripting! but running this from crontab, need first rows to set environment for graphics DISPLAY, of course I use in Ubuntu with WAYLAND.

**Comment by hhannine** [comment]
Thanks, I have noticed and been bothered by this issue in the past as well but I haven't been able to find the cause. Any help tracking down what's causing it would be greatly appreciated.

**Comment by Rob-00t** [comment]
After few months, I decided to rebuild my Ubuntu PC, and start from scratch with Ubuntu 24.04.
After install superpaper with pipx methods (instead of force to install into a default Ubuntu  python environment), the previous  behaviors disappears.
Now when wallpaper change, the memory, is increased for 1 second till 600/700 MB, and then is  automatically reduced to average  90 MB.
Probably, something was wrong in my previous Ubuntu build, that was upgraded though LTS versions for many years.

For that reason, I suggest to close this issue.
