### ISSUE TITLE
Question: Autostart

### ISSUE THREAD

**Issue by breznik** [hhannine/Superpaper#15]
Hi,

I got the portable linux release running on debian/gnome3. It seems like to provide it with a path to a directory of images, it's only possible through the GUI config. Is it possible to launch superpaper and use the profile I created on startup without having to start the GUI every boot?

Thanks!

**Comment by hhannine** [comment]
Hi,
Currently a profile can be active only if the tray application is running. However it should be possible to run the tray application at startup without opening the configuration GUI; this should be the default behavior if the help dialog at application startup is disabled.
