### ISSUE TITLE
No GUI on KDE Plasma 6/ Wayland

### ISSUE THREAD

**Issue by kinoegit** [hhannine/superpaper#150]
**Describe the bug**
App/ GUI does not start on KDE/Plasma 6/ Wayland

**To Reproduce**
run as Appimage:
```
./Superpaper-2.2.1-x86_64.AppImage 
/tmp/.mount_SuperpZQ0DNk/usr
/home/kinoe/.config/superpaper
/home/kinoe/.config/superpaper/profiles
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so

(Superpaper-2.2.1-x86_64.AppImage:30508): GdkPixbuf-WARNING **: 18:11:00.398: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(Superpaper-2.2.1-x86_64.AppImage:30508): Gtk-WARNING **: 18:11:00.403: Theme parsing error: gtk.css:3376:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 18:11:00.429: Failed to load module "colorreload-gtk-module"
Gtk-Message: 18:11:00.429: Failed to load module "window-decorations-gtk-module"
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-yes-antialias.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"

(Superpaper-2.2.1-x86_64.AppImage:30508): GdkPixbuf-WARNING **: 18:11:00.442: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

** (Superpaper-2.2.1-x86_64.AppImage:30508): WARNING **: 18:11:25.472: atk-bridge: get_device_events_reply: unknown signature
```
running:
```
gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache                                                                                             
zsh: file or directory not found: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
```

run as pacman installed AUR-package (version 2.2.1):
```
superpaper                                                       
/usr/lib/python3.12/site-packages
/home/kinoe/.config/superpaper
/home/kinoe/.config/superpaper/profiles

(superpaper:33310): Gtk-CRITICAL **: 18:15:43.723: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Expected behavior**
GUI should start

**Desktop:**
Operating System: Arch Linux 
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.9.3-arch1-1 (64-bit)
Graphics Platform: Wayland
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by HanSyt** [comment]
I can confirm this behaviour, KDE Neon latest Wayland.  More specific:
After install it gives the gui. Choose the desired wallpaper, apply it works.
As soon as the wallpaper is applied the gui does not show up again

My install was the native linux install - python3-pip, python3-wx<bla>, pip3 install superpaper
Worked fine with older KDE version, on Xorg server.

**Comment by MitchVanHayden** [comment]
The same here, as HanSyt, have mentioned it.
System: Nobara 39 and 40 with KDE

**Comment by Ironwally** [comment]
I have a similar problem. Error is different though.

System:
Debian 12
KDE Plasma
Wayland

Error:
/tmp/.mount_SuperpDYQ3H9/usr
/home/coban/.config/superpaper
/home/coban/.config/superpaper/profiles
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(Superpaper-2.2.1-x86_64.AppImage:36586): Gtk-WARNING **: 10:16:33.306: Theme parsing error: gtk-dark.css:426:34: 'font-feature-settings' is not a valid property name

(Superpaper-2.2.1-x86_64.AppImage:36586): Gtk-WARNING **: 10:16:33.307: Theme parsing error: gtk-dark.css:1026:81: 'font-feature-settings' is not a valid property name

(Superpaper-2.2.1-x86_64.AppImage:36586): Gtk-WARNING **: 10:16:33.307: Theme parsing error: gtk-dark.css:1071:85: 'font-feature-settings' is not a valid property name
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-yes-antialias.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "description"

(Superpaper-2.2.1-x86_64.AppImage:36586): Gtk-WARNING **: 10:16:33.526: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/breeze/status/64/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /tmp/_MEI1G0p3F/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.72) (gdk-pixbuf-error-quark, 5)
Abgebrochen (Speicherabzug geschrieben)

**Comment by Cris70** [comment]
I cannot confirm. I have SuperPaper 2.2.1 installed on openSuse Tumbleweed with KDE Plasma 6.1.5 (native package from openSuse repo) and the GUI works ok.

**Comment by kinoegit** [comment]
> I cannot confirm. I have SuperPaper 2.2.1 (native package from openSuse repo) installed on openSuse Tumbleweed with KDE Plasma 6.1.5 and the GUI works ok.

Thanks for your feedback. Would you mind to post the output of: `/usr/bin/python3 -m superpaper --debug`  or `superpaper --debug` here?

**Comment by Cris70** [comment]
> Thanks for your feedback. Would you mind to post the output of: `/usr/bin/python3 -m superpaper --debug` or `superpaper --debug` here?

Here it is:
```
cris ~ > superpaper --debug
/usr/lib/python3.11/site-packages
/home/cris/.config/superpaper
/home/cris/.config/superpaper/profiles
Input images: None
Input profile: None
Input perspective: None
Input spangroups: None
Input offsets: None
User defined command: None
Debugging: True

(superpaper:164919): Gtk-WARNING **: 18:55:44.261: Theme parsing error: gtk.css:1090:0: Expected a valid selector
use_hotkeys: False
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')

(superpaper:164919): Gtk-CRITICAL **: 18:55:44.295: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1680, 1050), (1920, 1080)], OFF_ARR = [(0, 0), (1680, 0)]
Display(resolution=(1680, 1050), digital_offset=(0, 0), phys_size_mm=(434, 270), detected_phys_size_mm=(434, 270), ppi=98.32258064516128, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DVI-D-1')
Display(resolution=(1920, 1080), digital_offset=(1680, 0), phys_size_mm=(521, 293), detected_phys_size_mm=(521, 293), ppi=93.6046065259117, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
config.sections: ['6495387272282202597']
DisplaySystem loaded: P.N.Offs: [(0.0, 0.0), (1679.1774661571908, 9.451280297320023)], bezel_mmṣ: [(0.0, 0.0), (0.0, 0.0)], user_diagonal_inches: None, use_perspective: True, def_perspective: None
update_bezels: (0.0, 0.0)
update_bezels: (0.0, 0.0)
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1680, 1050), (1920, 1080)], OFF_ARR = [(0, 0), (1680, 0)]
Display(resolution=(1680, 1050), digital_offset=(0, 0), phys_size_mm=(434, 270), detected_phys_size_mm=(434, 270), ppi=98.32258064516128, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DVI-D-1')
Display(resolution=(1920, 1080), digital_offset=(1680, 0), phys_size_mm=(521, 293), detected_phys_size_mm=(521, 293), ppi=93.6046065259117, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
config.sections: ['6495387272282202597']
DisplaySystem loaded: P.N.Offs: [(0.0, 0.0), (1679.1774661571908, 9.451280297320023)], bezel_mmṣ: [(0.0, 0.0), (0.0, 0.0)], user_diagonal_inches: None, use_perspective: True, def_perspective: None
update_bezels: (0.0, 0.0)
update_bezels: (0.0, 0.0)
running profile job with profile: cris1
['/home/cris/Pictures/Sfondi/dual-monitor/mountain_sky.jpg']
get_ppi_norm_offsets: [(0.0, 0.0), (1679.1774661571908, 9.451280297320023)]
get_ppi_norm_crops: [(0, 0, 1680, 1050), (1679, 9, 3696, 1143)]
G_A_DSYS.use_perspective: True, prof.perspective: default
Canvas size: [3600, 1080]
file:///home/cris/.cache/superpaper/temp/cris1-b.png
DESKTOP_SESSION is: 'plasmawayland'
Removing images matching with: 'cris1-a-crop'

^C
```

When it paused I stopped it.
Do you want me to let it run while I do something in particular?

**Comment by kinoegit** [comment]
Thanks for your help.
Your output shows: `DESKTOP_SESSION is: 'plasmawayland'`. Mine has got: `DESKTOP_SESSION is: 'plasma'` without the `wayland`
Maybe thats a hint to the problem?

**Comment by Cris70** [comment]
Yes, that could very well be the problem (or part of it).
Maybe your installation does not correctly recognize the desktop protocol.
Or maybe it is due to the different software levels among our Plasma installations... here are the complete details of my system:
```
Operating System: openSUSE Tumbleweed 20241005
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.3
Kernel Version: 6.11.0-1-default (64-bit)
Graphics Platform: Wayland

```

**Comment by kinoegit** [comment]
Operating System: Arch Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.3
Kernel Version: 6.11.2-arch1-1 (64-bit)
Graphics Platform: Wayland

**Comment by Cris70** [comment]
> Operating System: Arch Linux KDE Plasma Version: 6.1.5 KDE Frameworks Version: 6.6.0 Qt Version: 6.7.3 Kernel Version: 6.11.2-arch1-1 (64-bit) Graphics Platform: Wayland

So you updated?
Do you still have the problem?

**Comment by kinoegit** [comment]
> So you updated? Do you still have the problem?

Yes, still no GUI, though wallpaper changes as intended, when running `superpaper` or `superpaper.AppImage`
```
superpaper --debug
/usr/lib/python3.12/site-packages
/home/kinoe/.config/superpaper
/home/kinoe/.config/superpaper/profiles
Input images: None
Input profile: None
Input perspective: None
Input spangroups: None
Input offsets: None
User defined command: None
Debugging: True
use_hotkeys: False
hk_binding_next: ('control', 'shift', 'n')

(superpaper:207377): Gtk-CRITICAL **: 16:13:59.266: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1920, 1080)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(527, 296), detected_phys_size_mm=(527, 296), ppi=92.53889943074003, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-2')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(527, 296), detected_phys_size_mm=(527, 296), ppi=92.53889943074003, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
config.sections: ['7609373442098865376']
load: system not found with hash 1470267795684039387
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1920, 1080)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(527, 296), detected_phys_size_mm=(527, 296), ppi=92.53889943074003, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-2')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(527, 296), detected_phys_size_mm=(527, 296), ppi=92.53889943074003, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
config.sections: ['7609373442098865376']
load: system not found with hash 1470267795684039387
running profile job with profile: blob
['/home/kinoe/Wallpapers/Dualmonitor/aktuell/f33553.png']
get_ppi_norm_offsets: [(0, 0), (1920, 0)]
get_ppi_norm_crops: [(0, 0, 1920, 1080), (1920, 0, 3840, 1080)]
G_A_DSYS.use_perspective: True, prof.perspective: default
Canvas size: [3840, 1080]
file:///home/kinoe/.cache/superpaper/temp/blob-a.png
DESKTOP_SESSION is: 'plasma'
Removing images matching with: 'blob-b-crop'
```
"blob" is the name of the profile

**Comment by kinoegit** [comment]
As I didn't get the hang of that issue, I cleared the content of ~/config/superpaper except the profile folder.
Don't know why I didn't come up with that idea before: issue fixed! GUI is working as expected again! Even though it still says: `DESKTOP_SESSION is: 'plasma'` and not `DESKTOP_SESSION is: 'plasmawayland'`

**Comment by kinoegit** [comment]
Now that the GUI opens every time, even if I just want to choose a different wallpaper, I realise how much I've got used to using superpaper without the GUI.
Does anyone know how to simply change the wallpaper image according to prconfigured profile by using a (cli) command without using the GUI? Cli usage cmd: `superpaper --profile nameofprofile` lets me do that _but only via the GUI_!
