### ISSUE TITLE
[Feature request] separate image for only one of the displays / exclude one of the displays

### ISSUE THREAD

**Issue by vizitys** [hhannine/superpaper#151]
Hi! I'm loving the project, but I have a specific issue with my setup. 
I am currently running two monitors side by side, for which the advanced span works fine, but I recently got a TV which is also attached to my PC via an HDMI cord. The TV is off to the side, and most of the time it's off, so I don't need the wallpaper to span all the way over there. I would like for the TV to be able to have its own image. There is the span mode option called "separate image for every display", but I can't find an option to exclude only one of the displays.
Is there such an option? Is this in the scope of the project? Thanks!

**Comment by hhannine** [comment]
Have you tried the spanning groups feature in advanced mode? I made that exactly for something like this.

**Comment by vizitys** [comment]
> Have you tried the spanning groups feature in advanced mode? I made that exactly for something like this.

Ah, I don't know how I didn't see that! Thanks!
