### ISSUE TITLE
wx issue

### ISSUE THREAD

**Issue by zanagraf** [hhannine/superpaper#155]
**Describe the bug**
Try to launch Superpaper on Garuda gnome 47 (here is my inxi [sup.txt](https://github.com/user-attachments/files/17350096/sup.txt) ) but after set a venv, pip install... + requirement  (system_hotkey was missing), i got the error on "screenshots"

**To Reproduce**
1. Set Venv
3. source
4. pip install...
5. superpaper (and superpaper -d)
6. See error in Screenshots

**Expected behavior**
I want it work to have 2 different wallpaper for my 2 screen ^^

**Screenshots**
```
superpaper -d                                                                     ⌂/app py ⌉⌊ 3.12.7 16:49
/home/agraf/app/.venv/lib/python3.12/site-packages
/home/agraf/.config/superpaper
/home/agraf/.config/superpaper/profiles
Traceback (most recent call last):
  File "/home/agraf/app/.venv/bin/superpaper", line 5, in <module>
    from superpaper.__main__ import main
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/superpaper/__main__.py", line 13, in <module>
    from superpaper.cli import cli_logic
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/superpaper/cli.py", line 9, in <module>
    from superpaper.data import CLIProfileData
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/superpaper/data.py", line 16, in <module>
    from superpaper.message_dialog import show_message_dialog
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/superpaper/message_dialog.py", line 3, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

```

**Desktop (please complete the following information):**
 - OS: Garuda Linux (Arch)
 - Desktop Environment on Linux: Gnome 47
 - Superpaper package & version: [e.g. AppImage 2.0.2, Windows installer 2.0.2, PyPI 2.0.2]

**Comment by hhannine** [comment]
You need to install wx-python either from your distro repos or with pip. There should be some instructions in the guide.

**Comment by zanagraf** [comment]
Thanks for your reply!

I installed wx with pacman or yay first (do not remember) then i start installing under a fish venv.

After i did also a pip install of all the requirements text file of the github repo.

Then i restart the installation. Perhaps i had to uninstall before? I'll try.

I mean perhaps it's coming from fish... I can go to zsh if it can help. (I just move to fish, i like it but i can move^^)

One more thanks !

**Comment by zanagraf** [comment]
perhaps the wx in arch python wasn't the good one, i'm actually install by the website instruction with 

`pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
    wxPython`

it launch with this lines 
`superpaper                                                                          ⌂/app py ⌉⌊ 3.12.7 11:18
/home/agraf/app/.venv/lib/python3.12/site-packages
/home/agraf/.config/superpaper
/home/agraf/.config/superpaper/profiles

(superpaper:33104): Gtk-WARNING **: 11:18:12.531: Theme parsing error: gtk.css:6703:68: Invalid name of pseudo-class

(superpaper:33104): Gtk-WARNING **: 11:18:12.557: Theme parsing error: gtk-dark.css:6703:68: Invalid name of pseudo-class
Exception ignored in thread started by: <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x7a0a870f9760>>
Traceback (most recent call last):
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/system_hotkey/util.py", line 37, in call_functions
    func(*args, **kwargs)
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/system_hotkey/system_hotkey.py", line 284, in register
    assert isinstance(hotkey, collections.Iterable) and type(hotkey) not in (str, bytes)
                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Iterable'

(superpaper:33104): Gtk-CRITICAL **: 11:19:48.779: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
Traceback (most recent call last):
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/superpaper/gui.py", line 1035, in onApply
    saved_file = self.onSave(None)
                 ^^^^^^^^^^^^^^^^^
  File "/home/agraf/app/.venv/lib/python3.12/site-packages/superpaper/gui.py", line 1085, in onSave
    tmp_profile.perspective = self.ch_persp.GetString(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /tmp/pip-install-hqw755am/wxpython_b3b5617df5c94e47abef5e0151c5eae5/ext/wxWidgets/src/gtk/choice.cpp(303) in GetString(): invalid index
`

and it works ^^ i need to learn how but it works ^^!! thanks for this beautiful app !
