### ISSUE TITLE
Complex UX

### ISSUE THREAD

**Issue by wildeyes** [hhannine/superpaper#16]
it would be helpful to add "common scenarios" and how to accomplish them.
loved that the package has it's own name instead of "monitor-" whatever.

I tried setting up a rotating wallpapers for one screen but gave up after a few minutes. Bonus is if I could have a "vertical folder" for my second screen.

**Comment by hhannine** [comment]
The example profiles that come with Superpaper aim to help with getting started, but I do admit that the learning curve is a bit steep and not every setting is quite self explanatory. Reading the help hopefully is helpful.

The "example_multi" is a barebones example of what to do to get different wallpapers on each monitor and so following that you can give one monitor a folder of vertical wallpapers and another one a folder of horizontal wallpapers.
