### ISSUE TITLE
Bezel's not working with three monitors

### ISSUE THREAD

**Issue by ekce** [hhannine/superpaper#17]
I have three monitors in portrait mode aligned side by side. When I run superpaper it only adds crops the bezel between monitors 1 and 2, but not between monitors 2 and 3.

Here is my profile:
```
name=profile 1
spanmode=single
slideshow=False
delay=600
sortmode=shuffle
diagonal_inches=21.5;21.5;21.5
offsets=0,0;0,0;0,0
bezels=17.8;17.8;17.8
display0paths=/home/ekce/data/wallpapers
```
This is the image produced with that profile while when clicking on `Align Test`.
![cli-b](https://user-images.githubusercontent.com/3952493/70297251-8ca93500-17aa-11ea-94cc-a29a5edeac21.png)

I am using superpaper version 1.1.2 on Archlinux installed via this Aur package.
https://aur.archlinux.org/packages/superpaper/#comment-719530

**Comment by hhannine** [comment]
Thank you for the report. I think I've got the issue pinned down. I'll do some more testing before I push the changes, I had made some oversights in the original design of the feature so I'll make some changes that need testing.

**Comment by hhannine** [comment]
I've pushed the changes to the development branch, available here 7e98623c.
The feature now expects one length in millimeters for every crossed pair of bezels, so for 3 displays it wants 2 values. They are intended to be calculated as "bezel of display to the left + gap + bezel of the display to the right" added to a single number.

Could you test it? If you have the dependencies installed I guess the easiest way would be to clone the repo and just run the script.

**Comment by hhannine** [comment]
@ekce Have you had a chance to test this? I'm looking into making a new release soon and if you've tested it you could save me the work of setting up a 3 display virtual machine.

**Comment by hhannine** [comment]
This should be fixed in the recently released 1.2.0.
I'll close this for now but if the issue persists report back.

**Comment by ekce** [comment]
@hhannine Sorry, I hadn't been in my office to test. I just checked with the latest version and it works great now! Thanks!

**Comment by hhannine** [comment]
Thank you for testing it!
