### ISSUE TITLE
Not changing wallpaper in Ubuntu 19.04 (Gnome)

### ISSUE THREAD

**Issue by logix2** [hhannine/Superpaper#2]
I'm using Superpaper 1.1.1 in Ubuntu 19.04 with Gnome 3.32. Superpaper does not change the wallpaper on my computer. I tried setting ```gsettings set org.gnome.desktop.background picture-uri file://{image}``` as the custom command too, but it didn't work either. 

This is the log:
```
$ ./superpaper -d
None
None
None
None
None
None
True

(superpaper:9166): Gtk-WARNING **: 13:18:29.152: Theme parsing error: gtk.css:1:114: Failed to import: Error opening file /home/logix/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet.css: No such file or directory

(superpaper:9166): Gtk-WARNING **: 13:18:29.152: Theme parsing error: gtk.css:2:120: Failed to import: Error opening file /home/logix/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet-tiled.css: No such file or directory
Gtk-Message: 13:18:29.189: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:18:29.190: Failed to load module "canberra-gtk-module"
use_hotkeys: True
hkBinding_next: ('control', 'super', 'w')
hkBinding_pause: ('control', 'super', 'shift', 'p')
getDisplayData output: nDisplays = 2, [(1920, 1080), (2560, 1080)], [(2560, 0), (0, 0)]
SORTED getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1080)], [(0, 0), (2560, 0)]
START Listing profiles for menu.
Computed PPIs: [102.906992514443, 88.11628680329193]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8562711303697346]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 24]
Bezel px calculation: resulting combined manual offset: [(0, 0), (62, 0)]
Listed profile: example
Computed PPIs: [102.906992514443, 88.11628680329193]
hkBinding:('control', 'super', 'shift', 'z')
relative pixel densities: [1.0, 0.8562711303697346]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 24]
Bezel px calculation: resulting combined manual offset: [(0, 0), (62, 0)]
Listed profile: example_multi
END Listing profiles for menu.
read profile name from 'running_profile':example_multi
Computed PPIs: [102.906992514443, 88.11628680329193]
hkBinding:('control', 'super', 'shift', 'z')
relative pixel densities: [1.0, 0.8562711303697346]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 24]
Bezel px calculation: resulting combined manual offset: [(0, 0), (62, 0)]
getDisplayData output: nDisplays = 2, [(1920, 1080), (2560, 1080)], [(2560, 0), (0, 0)]
SORTED getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1080)], [(0, 0), (2560, 0)]
running profile job with profile: example_multi
Running wallpaper slideshow.
['/home/logix/.config/variety/Favorites/6qbhmmp3atl11.jpg', '/home/logix/.config/variety/Favorites/6niifqxs0ns21.jpg']
Computed PPIs: [102.906992514443, 88.11628680329193]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8562711303697346]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 24]
Bezel px calculation: resulting combined manual offset: [(0, 0), (62, 0)]
Listed profile: example
Computed PPIs: [102.906992514443, 88.11628680329193]
hkBinding:('control', 'super', 'shift', 'z')
relative pixel densities: [1.0, 0.8562711303697346]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 24]
Bezel px calculation: resulting combined manual offset: [(0, 0), (62, 0)]
Listed profile: example_multi
Registering binding:                                     ('control', 'super', 'shift', 'x') for profile: example
Registering binding:                                     ('control', 'super', 'shift', 'z') for profile: example_multi
Canvas size: [4480, 1080]
file:///home/logix/Downloads/superpaper-portable-linux/temp/example_multi-a.png
DESKTOP_SESSION is: 'ubuntu'
GLib-GIO-Message: 13:18:31.946: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Tray icon was left-clicked.
Start profile: example_multi
Check if the starting profile is already running: example_multi
name check: example_multi, example_multi
['/home/logix/.config/variety/Favorites/m773uelsogm11.png', '/home/logix/.config/variety/Favorites/photo-1540458160222-ebefc27da72a.jpg']
Canvas size: [4480, 1080]
file:///home/logix/Downloads/superpaper-portable-linux/temp/example_multi-b.png
DESKTOP_SESSION is: 'ubuntu'
GLib-GIO-Message: 13:18:40.136: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
['/home/logix/.config/variety/Favorites/94n90cbp1to21.jpg', '/home/logix/.config/variety/Favorites/m773uelsogm11.png']
Canvas size: [4480, 1080]
file:///home/logix/Downloads/superpaper-portable-linux/temp/example_multi-a.png
DESKTOP_SESSION is: 'ubuntu'
GLib-GIO-Message: 13:18:42.576: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

**Comment by manderso7** [comment]
About the same thing is happening in Budgie 18.04, though I'm trying to use via the gui:
`➜ ./superpaper -d
None
None
None
None
None
None
True

(superpaper:23668): GdkPixbuf-WARNING **: 06:31:44.859: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
Gtk-Message: 06:31:44.895: Failed to load module "canberra-gtk-module"
Gtk-Message: 06:31:44.897: Failed to load module "canberra-gtk-module"
use_hotkeys: True
hkBinding_next: ('control', 'super', 'w')
hkBinding_pause: ('control', 'super', 'shift', 'p')
getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1200)], [(0, 0), (2560, 0)]
SORTED getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1200)], [(0, 0), (2560, 0)]
START Listing profiles for menu.
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
END Listing profiles for menu.
read profile name from 'running_profile':example_multi
hkBinding:('control', 'super', 'shift', 'z')
getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1200)], [(0, 0), (2560, 0)]
SORTED getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1200)], [(0, 0), (2560, 0)]
running profile job with profile: example_multi
Running a one-off wallpaper change.
['/home/manderso/Pictures/v_wallpapers/IMG_3429.jpg', '/home/manderso/Pictures/v_wallpapers/zdk77qw8bfv21.jpg']
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Registering binding:                                     ('control', 'super', 'shift', 'x') for profile: example
Registering binding:                                     ('control', 'super', 'shift', 'z') for profile: example_multi
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
use_hotkeys: True
hkBinding_next: ('control', 'super', 'w')
hkBinding_pause: ('control', 'super', 'shift', 'p')

(superpaper:23668): Gtk-WARNING **: 06:31:50.842: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(superpaper:23668): Gtk-WARNING **: 06:31:50.842: for_size smaller than min-size (0 < 16) while measuring gadget (node check, owner GtkCheckButton)

(superpaper:23668): Gtk-WARNING **: 06:31:50.843: Negative content height -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkButton)
Canvas size: [4480, 1200]
file:///home/manderso/Downloads/superpaper-portable-linux/temp/example_multi-a.png
DESKTOP_SESSION is: 'budgie-desktop'
GLib-GIO-Message: 06:31:53.042: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(process:23699): GLib-GIO-WARNING **: 06:31:53.042: unknown schema extension 'd'

(process:23699): GLib-GIO-WARNING **: 06:31:53.042: unknown schema extension 'd'

(superpaper:23668): Gtk-WARNING **: 06:31:57.703: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(superpaper:23668): Gtk-WARNING **: 06:31:57.704: for_size smaller than min-size (0 < 16) while measuring gadget (node check, owner GtkCheckButton)

(superpaper:23668): Gtk-WARNING **: 06:31:57.704: Negative content height -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkButton)
multi_test
multi
False
120
shuffle



control+super+shift+z
['/home/manderso/Pictures/v_wallpapers', '/home/manderso/Pictures/v_wallpapers']
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: multi_test
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: multi_test
Unreg hotkey ('control', 'super', 'shift', 'x')
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'w')
Unreg hotkey ('control', 'super', 'shift', 'z')
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: multi_test
Registering binding:                                     ('control', 'super', 'shift', 'x') for profile: example
Registering binding:                                     ('control', 'super', 'shift', 'z') for profile: example_multi
Registering binding:                                     ('control', 'super', 'shift', 'z') for profile: multi_test
Could not register hotkey: '('control', 'super', 'shift', 'z')' for profile: 'multi_test'.
It is already registered for another action.
multi_test
multi
False
120
shuffle




['/home/manderso/Pictures/v_wallpapers', '/home/manderso/Pictures/v_wallpapers']
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Listed profile: multi_test
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Listed profile: multi_test
Unreg hotkey ('control', 'super', 'shift', 'x')
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'w')
Unreg hotkey ('control', 'super', 'shift', 'z')
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Listed profile: multi_test
Registering binding:                                     ('control', 'super', 'shift', 'x') for profile: example
Registering binding:                                     ('control', 'super', 'shift', 'z') for profile: example_multi
Registering binding:                                     None for profile: multi_test
multi_test
multi
False
120
shuffle




['/home/manderso/Pictures/v_wallpapers', '/home/manderso/Pictures/v_wallpapers']
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Listed profile: multi_test
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Listed profile: multi_test
Unreg hotkey ('control', 'super', 'shift', 'x')
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'w')
Unreg hotkey ('control', 'super', 'shift', 'z')
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Listed profile: multi_test
Registering binding:                                     ('control', 'super', 'shift', 'x') for profile: example
Registering binding:                                     ('control', 'super', 'shift', 'z') for profile: example_multi
Registering binding:                                     None for profile: multi_test
/home/manderso/Downloads/superpaper-portable-linux/profiles/multi_test.profile
Computed PPIs: [102.906992514443, 90.56621886774339]
hkBinding:('control', 'super', 'shift', 'x')
relative pixel densities: [1.0, 0.8800783761611963]
Bezel px calculation: initial manual offset: [(0, 0), (0, 0)],                 and bezel pixels: [38, 25]
Bezel px calculation: resulting combined manual offset: [(0, 0), (63, 0)]
Listed profile: example
hkBinding:('control', 'super', 'shift', 'z')
Listed profile: example_multi
Listed profile: multi_test
Start profile: multi_test
Check if the starting profile is already running: multi_test
name check: multi_test, example_multi
Running quick profile job with profile: multi_test
quickswitch file lookup: []
Old file for quickswitch was not found. []
Starting timed profile job with profile: multi_test
getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1200)], [(0, 0), (2560, 0)]
SORTED getDisplayData output: nDisplays = 2, [(2560, 1080), (1920, 1200)], [(0, 0), (2560, 0)]
running profile job with profile: multi_test
Running a one-off wallpaper change.
['/home/manderso/Pictures/v_wallpapers/IMG_3405.jpg', '/home/manderso/Pictures/v_wallpapers/atl_skyline2.jpg']
Wrote active profile: multi_test
Canvas size: [4480, 1200]
file:///home/manderso/Downloads/superpaper-portable-linux/temp/multi_test-a.png
DESKTOP_SESSION is: 'budgie-desktop'
GLib-GIO-Message: 06:32:48.009: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
`
In Budgie, my display mode is set to "Join Displays". I've tried this with single and multi wallpaper options, with the same result of the background image not changing.

**Comment by hhannine** [comment]
Your issues probably are connected. Can you guys verify that the command
gsettings set org.gnome.desktop.background picture-uri file:///path/to/image
works for you from the terminal with an image of your choice?

Or alternatively do you know if it  is not the above, what the terminal command for setting the wallpaper is on your systems?

**Comment by logix2** [comment]
Yes, the command works from a terminal.

**Comment by hhannine** [comment]
Can you check out this answer related to gsettings and PATH? https://askubuntu.com/a/1007851

**Comment by manderso7** [comment]
That command to change the wallpaper works for me. However, I'm not certain what I should be doing by going to that link? I see /usr/bin/gsettings when I run which gsettings, but I'm not certain what I should be doing afterwards.
I'm running zsh instead of bash if it matters.

Thanks

**Comment by hhannine** [comment]
Thanks for reporting back. Yeah sorry for such an unspecific request, I mostly wanted to hear the output from 'which gsettings' which you found. I was shooting in the dark since the error that both of you get is strange to me: "GLib-GIO-Message: 06:32:48.009: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications."

I'll try to look into this what could cause this.

**Comment by dancaer69** [comment]
I just download and try it in Linux Mint 19.1 with cinnamon DE and seems that I have the same problem.
I also get this message:
`GLib-GIO-Message: 15:18:32.679: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.`

**Comment by hhannine** [comment]
> 
> 
> I just download and try it in Linux Mint 19.1 with cinnamon DE and seems that I have the same problem.
> I'm getting this message too:
> `GLib-GIO-Message: 15:18:32.679: Using the 'memory' GSettings backend. Your settings will not be saved or shared with other applications.`

dancaer, could you also post what you get from 'which gsettings' command?

**Comment by dancaer69** [comment]
Sure:
`/usr/bin/gsettings`

**Comment by hhannine** [comment]
Thanks @dancaer69. Unfortunately I haven't made any progress on this issue yet. As a workaround you could try to use the feh backend mode if you have feh installed. Set the custom command to "feh", check readme for details.

**Comment by dancaer69** [comment]
I tried to use feh but, if I set the command right, it doesn't work too. I tried to set "custom command" like this:
1. `feh --bg-fill {image}`
2. `feh --bg-fill file://{image}`
3. `feh --bg-fill picture uri file://{image}`
neither works.
When using feh or gsettings from command line like this:
`feh --bg-fill /path/to/image.jpg`
`gsettings set org.gnome.desktop.background picture-uri /path/to/image.jpg`
then the background changes.
I also tried with mate and openbox as DE and it doesn't work there also.

**Comment by hhannine** [comment]
I was finally able to look into why the custom commands weren't working: I've neglected to add to the README that one in fact needs to put second quotes around {image}, so the custom command string wound be
"feh --bg-fill '{image}'"

However, this is in fact equivalent to just specifying --command "feh".

**Comment by hhannine** [comment]
Correction, there was an issue with escaping spaces in the path. I'll push a fix for this in the near future. However, as I wrote above for the case of feh the additional quotes worked around the issue.

**Comment by hhannine** [comment]
I just pushed a fix to the path handling. Should now work without extra quotes, which would break gsettings command for example.

**Comment by hhannine** [comment]
Regarding the original issue, might you try this solution? https://stackoverflow.com/a/45223897
>export GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/

You can try this by only setting the variable in the scope of superpaper by running it as:
>GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ ./superpaper

**Comment by dancaer69** [comment]
I tried with feh custom command as you posted and it doesn't work also. I can see the images copied to "temp" folder and in terminal the correct path to the image, but every time I get "not found" errors and no image loaded.
Fortunately, using the command from your last reply is the only that works!

**Comment by hhannine** [comment]
Good to hear! Thanks for reporting back.

Just to double check before I close this issue as hopefully solved:
1. You used the command
`GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ ./superpaper`
and it worked?

2. You are using a release version (the executable) and not the script from the master branch from Github? The release versions don't yet have the fix I was talking about above.

**Comment by dancaer69** [comment]
1. yes.
2. Yes, I'm using the executable. I know that, I checked first the releases and there wasn't  a today' s version. I tried the source code also, because the executable version is quite large(probably because include all python libraries the app uses) but I get an error(segmentation fault I think). I will try it again and I' ll report back.

**Comment by hhannine** [comment]
Thanks a lot @dancaer69!

It seems like the issues have been resolved and fixed in the next release so I'll close this issue.

**Comment by manderso7** [comment]
So cloning from the repo should allow this to work now?

**Comment by hhannine** [comment]
> 
> 
> So cloning from the repo should allow this to work now?

Right now, by cloning you get the fix for the custom command issue described by @dancaer69.

By running Superpaper with the command
`GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ ./superpaper`
you should get a fix for the gsettings issue that you had
>
>GLib-GIO-Message: 06:32:48.009: Using the 'memory' GSettings backend.
