### ISSUE TITLE
AppImage does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [hhannine/superpaper#29]
Thanks for making an AppImage. 

However, it fails to run on Ubuntu xenial:

```
[6] Error loading Python lib '/tmp/_MEIuTLFXW/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIuTLFXW/libpython3.7m.so.1.0)
```

Please build on a system no newer than the oldest still-supported Ubuntu LTS release, which is xenial at this time. Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1882

**Comment by hhannine** [comment]
Thanks for bringing this up. I'm planning to fix this for the next release.

**Comment by hhannine** [comment]
Whilst trying to setup a 16.04 LTS build environment in a virtual machine I found out that wxPython 4.0 is not available prior to bionic 18.04 LTS. I guess I'm forced to build the appimages on bionic.

**Comment by probonopd** [comment]
No, you can also build wxPython on xenial.

**Comment by hhannine** [comment]
Indeed, thanks for the reminder.
I packaged an AppImage in the VM with linuxdeploy but I get an error "Cannot open self ... or archive ...".
Would you have any idea what could cause this?

I tested that the xenial built binary won't run on my RHEL 7 machine at work. Would the RHEL machine be a good build base?

**Comment by hhannine** [comment]
Quickly tested building the AppImage on the RHEL machine as well and I get the same issue, the resulting AppImage fails to run with the above error. I'm using linuxdeploy to build the appimage.

**Comment by hhannine** [comment]
I was able to fix that error by downgrading some pip packages. I'll document working build setup for myself here:

-python 3.6
-pyinstaller 3.5
-setuptools 44.0.0
-dbus-python from pip

It remains unclear if the newest build of linuxdeploy had some part in this, I got this working with a copy of an older build from my notebook.

The new AppImage would seem to run ok on xenial but I still need to update the packaging script to include new resources.

**Comment by probonopd** [comment]
Thanks for looking into this @hhannine, please ping me once you think the AppImage is ready for another test at https://github.com/AppImage/appimage.github.io/pull/1882.

**Comment by hhannine** [comment]
I built a new test Appimage of the upcoming release on a Xenial VM but unfortunately the UI is stylistically broken although usable on my Manjaro machine and nigh on completely broken on my Kubuntu 19.10 machine. I'm a bit at a loss on how to fix it.

**Comment by hhannine** [comment]
I've got 2 testing AppImages; since they're large I shared them from Google Drive
1. Built on Xenial, runs on Xenial VM and somewhat usably on Manjaro KDE: [xenial-testing](https://drive.google.com/file/d/1n_7k7vnY6L4W9vK4SHmybyXAlruczeFh/view)
2. Built on RHEL7, runs on RHEL, Ubuntu 18.04 VM, Kubuntu 19.10, Manjaro KDE: [rhel-testing](https://drive.google.com/file/d/1qApOtSqnlK6tmZ7-nI_r9p5V7Fh1iyGm/view)

@probonopd, if you, or anyone else for that matter, test these I'd like to hear how it goes.

**Comment by probonopd** [comment]
Thank you, the Xenial one passed the test successfully on first try. Didn't check the other one. Will you upload it to GitHub Releases? Then I will re-run the automated test again. Thanks.

**Comment by hhannine** [comment]
Thank you. I'm hoping to fix some small things and make a stable release in a few days; I'll ping you once they're up on releases.

**Comment by hhannine** [comment]
@probonopd , the new appimage is now up at releases.

**Comment by probonopd** [comment]
Thank you very much :+1:
