### ISSUE TITLE
Crash on start in Windows 10

### ISSUE THREAD

**Issue by OskarPersson** [hhannine/superpaper#37]
The application fails to start on Windows 10 (Pro Version 1909, build 18363.778). No window ever appears and I get no error message. I've tried both the portable and installer version.

**Comment by hhannine** [comment]
Try to run the portable version with the debug flag -d from the command prompt?

If that doesn't work try to change the general_settings file to have logging=true and see if the log file is made?

**Comment by OskarPersson** [comment]
Here is the contents of the log file:

```
Enabled logging to file.
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
Uncaught exception type: <class 'wx._core.wxAssertionError'>
NoneType: None
Exception: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1699) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
NoneType: None
<traceback object at 0x00000213FD8D2940>
NoneType: None
```

**Comment by hhannine** [comment]
Thank you. Unfortunately the issue seems to somewhat non-trivial and I've not run into it before.

What locale are you using your Windows in? Is system default language something else than english?

**Comment by OskarPersson** [comment]
The Windows Display Language is set to English (United States).

The "Preferred languages" are in the following order:

1. English (United States)
Default app language
Windows display language

2. English (Sweden)
3. Svenska (Sverige) (which means "Swedish (Sweden)")
Default input language

**Comment by hhannine** [comment]
Well that's strange; my languages are very similar if not exactly the same with the replacement of Swedish -> Finnish.

I'll have to research this issue.

**Comment by hhannine** [comment]
I repackaged the windows files, would you test them if they work for you? The new files have "hotfix" in the name.

**Comment by OskarPersson** [comment]
Works great, thanks!

**Comment by hhannine** [comment]
Superb, thank you. I'll close this and replace the original packages.
