### ISSUE TITLE
Manage Window Sizes Please

### ISSUE THREAD

**Issue by pavangayakwad** [hhannine/superpaper#41]
If you observe the screenshot, even after me hiding top-bar and dock, It is impossible for me to see the buttons to select folder/files. It would be nice if screens are re-sizable.

![image](https://user-images.githubusercontent.com/1834890/81115419-4ca8d280-8f41-11ea-9e7e-4bd62fb4603d.png)

**Comment by hhannine** [comment]
That's an unfortunate oversight, thanks for bringing it up. What is your resolution on the display you're trying to use it? Though I'll probably have to come up with a proper solution that results in reasonable window sizes on all kinds of displays.

**Comment by pavangayakwad** [comment]
Its 1366x768.

Thanks for your swift reply. Please allow windows to resize.

**Comment by hhannine** [comment]
Thanks. Yes, I will fix this for next release.

**Comment by hhannine** [comment]
Was the help dialog too tall / large as well?

**Comment by hhannine** [comment]
This should now be resolved with 00367a3b3ed4ae6c680925c900ab980794be0984, 8119827a8d60c2aa12fd165cb70a36826e775823
