### ISSUE TITLE
confused on correct way to start and end superpaper (Tray icon not showing up on Ubuntu 18.04)

### ISSUE THREAD

**Issue by dln949** [hhannine/superpaper#43]
Ubuntu 18.04.4, gnome shell 3.28.4, superpaper ?????? (don't know how to find the version, but I just installed it today following the instruction at the PyPI site)

1)  I don't know how to start superpaper.  What I mean is, when I start it, it always brings me to the configuration window.  I don't need that, I just want it to "go", just start working.  How do I do that?  

2)  The documentation talks about an icon in the tray area, and through that to access settings.  But, I do not see any icon in the tray area.  (Icons for other programs appear there, but not any for superpaper.)  How do I get this mysterious icon to appear?  

3)  Also...  How does a person properly stop superpaper from running?

**Comment by hhannine** [comment]
Superpaper is supposed to be controlled from the tray applet / application indicator, see screenshot:
![image](https://user-images.githubusercontent.com/47873564/81143289-2f442a80-8f7a-11ea-8330-83b52349dafd.png)

1. If you disable the help at start dialog, then superpaper only runs into the system tray as an indicator.

2. Is your system tray working for other applications; something similar as in my screenshot? I must say that I'm quite unfamiliar with Gnome and I have not gotten the system tray working in a virtual machine, though this is for all applications.

I found that on Unity there's some unfixed bug that prevents the tray icons made with the UI library that superpaper uses to show up so I'm hoping it's not something that is affecting Gnome as well.


3. Superpaper is intended to be closed from the tray, as is seen in the screenshot.

**Comment by Danie10** [comment]
I think I have the same question - was it now to have it autostart on bootup and load a default or named profile, silently on boot up?

**Comment by hhannine** [comment]
When Superpaper starts it loads the previously applied / running profile if one is found. So to run it in the background after bootup disable the "show help at start" option so Superpaper only opens as a tray application and then in your OS start-up applications add Superpaper.

**Comment by Danie10** [comment]
@hhannine thanks that makes sense and I'll try that - working very nicely so far.

**Comment by dln949** [comment]
@hhannine :  

"Is your system tray working for other applications; something similar as in my screenshot? I must say that I'm quite unfamiliar with Gnome and I have not gotten the system tray working in a virtual machine, though this is for all applications."  

Yes, as I wrote in my original post, icons from other programs appear in the tray area just fine.  The only one that refuses to appear is Superpaper's.  How do I get this icon to appear?  

(Also, since the icon does not appear, how should I properly exit Superpaper if I need to?)

**Comment by hhannine** [comment]
Ok good to know, thanks for the clarification. Would you try to run superpaper with the debugging flag -d to see if there's any error messages about the missing tray icon? Otherwise I'm going to have to look for solutions online, and test it myself.

To kill superpaper you can use the 'killall' command, I. E. ʼkillall superpaperʼ

**Comment by dln949** [comment]
Thanks.  

Ok, the output is below.  But, one other question first:  Until I get the tray icon working, how do I open the superpaper configuration window?  


Here is the output you asked for:  

main1@system1:~$ /home/main1/.local/bin/superpaper -d
/home/main1/.local/lib/python3.6/site-packages
/home/main1/.config/superpaper
/home/main1/.config/superpaper/profiles
None
None
None
None
None
None
True
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 49.07471698113207, ver: 65.024
Display(resolution=(1024, 768), digital_offset=(0, 0), phys_size_mm=(530, 300), detected_phys_size_mm=(530, 300), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI1')
WARNING: Horizontal and vertical PPI do not match! hor: 43.349333333333334, ver: 57.37411764705882
Display(resolution=(1024, 768), digital_offset=(1024, 0), phys_size_mm=(600, 340), detected_phys_size_mm=(600, 340), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI3')
WARNING: Horizontal and vertical PPI do not match! hor: 51.09941060903732, ver: 68.206993006993
Display(resolution=(1024, 768), digital_offset=(2048, 25), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='VGA1')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1024, 768), (1024, 768), (1024, 768)], OFF_ARR = [(0, 0), (1024, 0), (2048, 25)]
Display(resolution=(1024, 768), digital_offset=(0, 0), phys_size_mm=(530, 300), detected_phys_size_mm=(530, 300), ppi=49.07471698113207, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI1')
Display(resolution=(1024, 768), digital_offset=(1024, 0), phys_size_mm=(600, 340), detected_phys_size_mm=(600, 340), ppi=43.349333333333334, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI3')
Display(resolution=(1024, 768), digital_offset=(2048, 25), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=51.09941060903732, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='VGA1')
config.sections: ['5068152087252660579']
DisplaySystem loaded: P.N.Offs: [(0.0, 50.59984145166494), (1431.252658204237, 0.0), (2949.247901754185, 50.59984145166494)], bezel_mmṣ: [(52.37, 10.91), (23.01, 0.0), (0.0, 0.0)], user_diagonal_inches: [24.0, 27.2, 19.0], use_perspective: False, def_perspective: default
update_bezels: (105.35732809430255, 21.94860510805501)
update_bezels: (46.29123772102161, 0.0)
update_bezels: (0.0, 0.0)
Updating diagonal_inches
Updated PPI = 53.333333333333336 and phys_size_mm = (487.67999999999995, 365.75999999999993) based on diagonal size: 24.0 inches
Display(resolution=(1024, 768), digital_offset=(0, 0), phys_size_mm=(487.67999999999995, 365.75999999999993), detected_phys_size_mm=(530, 300), ppi=53.333333333333336, ppi_norm_resolution=(1066, 800), ppi_norm_offset=(0.0, 50.59984145166494), ppi_norm_bezels=(105.35732809430255, 21.94860510805501), perspective_angles=(0, 0), name='HDMI1')
Updated PPI = 47.05882352941177 and phys_size_mm = (552.704, 414.52799999999996) based on diagonal size: 27.2 inches
Display(resolution=(1024, 768), digital_offset=(1024, 0), phys_size_mm=(552.704, 414.52799999999996), detected_phys_size_mm=(600, 340), ppi=47.05882352941177, ppi_norm_resolution=(1207, 905), ppi_norm_offset=(1431.252658204237, 0.0), ppi_norm_bezels=(46.29123772102161, 0.0), perspective_angles=(0, 0), name='HDMI3')
Updated PPI = 67.36842105263158 and phys_size_mm = (386.08, 289.55999999999995) based on diagonal size: 19.0 inches
Display(resolution=(1024, 768), digital_offset=(2048, 25), phys_size_mm=(386.08, 289.55999999999995), detected_phys_size_mm=(509, 286), ppi=67.36842105263158, ppi_norm_resolution=(1024, 768), ppi_norm_offset=(2949.247901754185, 50.59984145166494), ppi_norm_bezels=(0.0, 0.0), perspective_angles=(0, 0), name='VGA1')
Loading perspective profs: ['default']
START Listing profiles for menu.
perspective preset: default
Listed profile: default
END Listing profiles for menu.
read profile name from 'running_profile': default
perspective preset: default
WARNING: Horizontal and vertical PPI do not match! hor: 49.07471698113207, ver: 65.024
Display(resolution=(1024, 768), digital_offset=(0, 0), phys_size_mm=(530, 300), detected_phys_size_mm=(530, 300), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI1')
WARNING: Horizontal and vertical PPI do not match! hor: 43.349333333333334, ver: 57.37411764705882
Display(resolution=(1024, 768), digital_offset=(1024, 0), phys_size_mm=(600, 340), detected_phys_size_mm=(600, 340), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI3')
WARNING: Horizontal and vertical PPI do not match! hor: 51.09941060903732, ver: 68.206993006993
Display(resolution=(1024, 768), digital_offset=(2048, 25), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='VGA1')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1024, 768), (1024, 768), (1024, 768)], OFF_ARR = [(0, 0), (1024, 0), (2048, 25)]
Display(resolution=(1024, 768), digital_offset=(0, 0), phys_size_mm=(530, 300), detected_phys_size_mm=(530, 300), ppi=49.07471698113207, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI1')
Display(resolution=(1024, 768), digital_offset=(1024, 0), phys_size_mm=(600, 340), detected_phys_size_mm=(600, 340), ppi=43.349333333333334, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI3')
Display(resolution=(1024, 768), digital_offset=(2048, 25), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=51.09941060903732, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='VGA1')
config.sections: ['5068152087252660579']
DisplaySystem loaded: P.N.Offs: [(0.0, 50.59984145166494), (1431.252658204237, 0.0), (2949.247901754185, 50.59984145166494)], bezel_mmṣ: [(52.37, 10.91), (23.01, 0.0), (0.0, 0.0)], user_diagonal_inches: [24.0, 27.2, 19.0], use_perspective: False, def_perspective: default
update_bezels: (105.35732809430255, 21.94860510805501)
update_bezels: (46.29123772102161, 0.0)
update_bezels: (0.0, 0.0)
Updating diagonal_inches
Updated PPI = 53.333333333333336 and phys_size_mm = (487.67999999999995, 365.75999999999993) based on diagonal size: 24.0 inches
Display(resolution=(1024, 768), digital_offset=(0, 0), phys_size_mm=(487.67999999999995, 365.75999999999993), detected_phys_size_mm=(530, 300), ppi=53.333333333333336, ppi_norm_resolution=(1066, 800), ppi_norm_offset=(0.0, 50.59984145166494), ppi_norm_bezels=(105.35732809430255, 21.94860510805501), perspective_angles=(0, 0), name='HDMI1')
Updated PPI = 47.05882352941177 and phys_size_mm = (552.704, 414.52799999999996) based on diagonal size: 27.2 inches
Display(resolution=(1024, 768), digital_offset=(1024, 0), phys_size_mm=(552.704, 414.52799999999996), detected_phys_size_mm=(600, 340), ppi=47.05882352941177, ppi_norm_resolution=(1207, 905), ppi_norm_offset=(1431.252658204237, 0.0), ppi_norm_bezels=(46.29123772102161, 0.0), perspective_angles=(0, 0), name='HDMI3')
Updated PPI = 67.36842105263158 and phys_size_mm = (386.08, 289.55999999999995) based on diagonal size: 19.0 inches
Display(resolution=(1024, 768), digital_offset=(2048, 25), phys_size_mm=(386.08, 289.55999999999995), detected_phys_size_mm=(509, 286), ppi=67.36842105263158, ppi_norm_resolution=(1024, 768), ppi_norm_offset=(2949.247901754185, 50.59984145166494), ppi_norm_bezels=(0.0, 0.0), perspective_angles=(0, 0), name='VGA1')
Loading perspective profs: ['default']
running profile job with profile: default
Running wallpaper slideshow.
/home/main1/Pictures/Wallpapers/image16.jpg
get_ppi_norm_offsets: [(0, 54), (1398.3573280943026, 0), (2910.648565815324, 166)]
get_ppi_norm_crops: [(0, 54, 1293, 1024), (1398, 0, 2864, 1099), (2911, 166, 3935, 934)]
G_A_DSYS.use_perspective: False, prof.perspective: default
perspective preset: default
Listed profile: default
Registering binding:                                 None for profile: default
Canvas size: [3072, 793]
file:///home/main1/.cache/superpaper/temp/default-b.png
DESKTOP_SESSION is: 'ubuntu'

**Comment by hhannine** [comment]
Thanks.

Unfortunately currently the only way to force the configuration to open without the tray icon is to have the help dialog open at start.

**Comment by dln949** [comment]
Oh, oh....  I had already unchecked that option.

**Comment by hhannine** [comment]
You can either edit ( or delete since you haven't been able to access the settings dialog to change anything, it'll be rewritten with defaults) the general_settings file in ~/. config/superpaper. The file is readable and fairly short if you choose to edit it, set the help option to equal true.

**Comment by Findarato** [comment]
Just adding in a cool error 

`/usr/lib64/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
10:27:41 AM: Debug: Failed to connect to session manager: Authentication Rejected, reason : MIT-MAGIC-COOKIE-1 authentication rejected
`

**Comment by dln949** [comment]
@Findarato , I'm the person who started this issue.  I am not a technical person, so I am not understanding what you are saying.  Are you saying that what you posted shows how to fix something I was asking about?  If so, I'm not understanding what I should be doing.  Thanks for any clarification.

**Comment by hhannine** [comment]
@Findarato is superpaper working for you or is that error causing a crash? The appimage is less than perfect and spits out all kinds of non critical junk depending on the host distro.

**Comment by hhannine** [comment]
@dln949 This is a bit suboptimal but I got the tray icon to show up in my Ubuntu 18.04 virtual machine by installing and enabling the "TopIcons plus" Gnome extension. Might be that the GUI library that creates the indicator uses some legacy pathway that creates an icon that is not shown on Gnome as default. Not sure. At least this is an easy fix.

**Comment by dln949** [comment]
@hhannine , thanks for your help with this, I appreciate it.  

Strangely, that very same idea occurred to me about an hour ago.  

The problem with TopIcons Plus is that it will eventually interefere with how the Ubuntu appindicator manages icons in the tray.  So, I installed Top Icons Plus, but only turn it on when I need to access the Superpaper icon, and then turn it off when I'm done.  Really, really suboptimal, but works.

**Comment by hhannine** [comment]
https://github.com/ubuntu/gnome-shell-extension-appindicator I wonder if this is a fork of the indicator extension you're using that would work?

What is the name of your preferred indicator extension so that I could possibly make an issue of this upstream?

**Comment by dln949** [comment]
My preferred extension is the one  you have the link to, also found here:  [https://extensions.gnome.org/extension/615/appindicator-support/](url)

**Comment by dln949** [comment]
My preferred extension is the one you have the URL link to, also found here:  

https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by okeshawarz** [comment]
Can confirm that the icon does not appear in the tray. I've tried all combinations of TopIconsPlus, the AppIndicator extension, and the Unity topbar tray option. I'm running Manjaro GNOME.
