### ISSUE TITLE
Can't download files from Releases

### ISSUE THREAD

**Issue by stramuchak** [hhannine/superpaper#46]
I tried to download the Windows executable file from releases but it fails and sends me to a page with the following message at the top: "This XML file does not appear to have any style information associated with it."

**Comment by hhannine** [comment]
It is working for me currently. Does the issue still persist? Downloads are hosted by GitHub so either they had an issue or maybe there could be a problem with the browser you're trying to download with.

**Comment by stramuchak** [comment]
Interesting, it works now. Thanks!
