### ISSUE TITLE
Perspective corrections: strong sensitivity to parameters in 4 display setup

### ISSUE THREAD

**Issue by adamwelsh** [hhannine/superpaper#49]
I'm using the windows installer client 2.02
For swivel and tilt angle, sane values are like 0.005 and -0.02.
If I use an integer it's insanely skewed.

**Comment by hhannine** [comment]
I'm going to need all the perspective settings you've inputted to be able to help. Maybe it's easiest to share a screenshot of the dialog.

**Comment by adamwelsh** [comment]
![superpaper-001](https://user-images.githubusercontent.com/57105060/81753848-8e69d980-9469-11ea-90bf-7a9a5f330547.JPG)

**Comment by hhannine** [comment]
Your view distance is set to 12 meters, is this accurate? The perceived amount of contortion can be very sensitive to the place you set your head to be at. It'll look wrong if you look at it from the wrong place.

If changing your position doesn't help would you share the problematic settings, a photo of what it looks like as the wallpaper and enable the log file in settings and share that of the problematic wallpaper application.

**Comment by adamwelsh** [comment]
You're right. it should have been 1200mm. Thank you and sorry.
I find it very difficult to get 4 monitors with tilt and swivel to look right. but thats on me. closing

**Comment by hhannine** [comment]
Good to hear that correcting that is helping. And no problem at all, I've not tested it with more than two displays, it must be quite tricky to get right with four. Good to get testers on more complex setups, always could be some mistake lurking in there.
