### ISSUE TITLE
Won't span on Cinnamon

### ISSUE THREAD

**Issue by robcampbell95** [hhannine/superpaper#50]
Linux localhost 5.6.8-300.fc32.x86_64 #1 SMP Wed Apr 29 19:01:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
cinnamon-desktop-4.4.1-2.fc32.x86_64
cinnamon-4.4.8-7.fc32.x86_64

Config:
Span mode: Advanced span

That's the only setting I've made.  It looks correct on the preview.

**Comment by hhannine** [comment]
Check that the Cinnamon background option is set to 'spanned'.

**Comment by robcampbell95** [comment]
Thanks.  That worked.  I was just coming to close this bc I just found that setting.
