### ISSUE TITLE
Windows - Advanced Span issue

### ISSUE THREAD

**Issue by cooltrooper** [hhannine/superpaper#51]
On my windows machine (1x 4k laptop screen in front of 2x 27" 1080p monitors, simple span works perfectly, but advanced span behaves very oddly.

All monitors get the same image, the left is half is part of an image, top right quater is another and the bottom right quater is black. Am i doing something wrong?

Manually setting the wallpaper mode to span in windows seems to help a little.

**Comment by hhannine** [comment]
I see you changed the Windows personalization background fitting style set to 'span'. What does it look like after that? Is the monitor positions configured correctly in the advanced mode preview?

**Comment by hhannine** [comment]
How did this turn out? Is there still an issue?

**Comment by hhannine** [comment]
If there still is an issue with the background fit set to 'span' in Windows 10 personalization settings, come post a new comment with a screencap of your preview and settings and a photo of what it looks like as the set wallpaper on the displays and we'll look at it again.

Meanwhile I'll assume this is resolved and close this for now.
