### ISSUE TITLE
"Image not found" errors after changing folder structure in explorer

### ISSUE THREAD

**Issue by painfield** [hhannine/superpaper#54]
**Describe the bug**
When changing the folder structure where the images are stored, the software can't find images added individually and enters in an error popup loop that doesn't let change the paths, even if a different profile is running.

**To Reproduce**
1. Create a folder structure.
2. Add individual image from inside the folder structure.
3. Change folder structure so it modifies the path of the image.
4. When applying the popup keeps appearing preventing you from correcting the paths.

**Expected behavior**
Being able to correct it after the first error popup per image at least.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Superpaper package & version: Windows installer 2.0.2

**Additional context**
When uninstalling it doesn't delete the profiles.
I found the C:\Users\*****\AppData\Local\Superpaper and was able to delete the profiles and solve the problem.

**Comment by hhannine** [comment]
Thanks. I'll need to redesign the error handling. Good that you were able to delete the problematic profile.
