### ISSUE TITLE
What does this error on Arch mean?

### ISSUE THREAD

**Issue by Strykar** [hhannine/superpaper#59]
Bit related to https://github.com/hhannine/superpaper/issues/53 and https://github.com/hhannine/superpaper/issues/55 but since the aur packager has not responded to comments there, I would like some pointers on the error as I do not know Python.

```
superpaper
/usr/lib/python3.8/site-packages
/home/tio/.config/superpaper
/home/tio/.config/superpaper/profiles
Traceback (most recent call last):
  File "/usr/bin/superpaper", line 11, in <module>
    load_entry_point('superpaper==2.0.2', 'console_scripts', 'superpaper')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/superpaper/__main__.py", line 13, in <module>
    from superpaper.cli import cli_logic
  File "/usr/lib/python3.8/site-packages/superpaper/cli.py", line 8, in <module>
    from superpaper.data import CLIProfileData
  File "/usr/lib/python3.8/site-packages/superpaper/data.py", line 15, in <module>
    import superpaper.wallpaper_processing as wpproc
  File "/usr/lib/python3.8/site-packages/superpaper/wallpaper_processing.py", line 19, in <module>
    from PIL import Image, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (/usr/lib/python3.8/site-packages/PIL/__init__.py)
```

**Comment by hhannine** [comment]
Yeah the issue is that Pillow 7 is not available on AUR so the superpaper package there has been patched to work with Pillow 6. But the latest release patch is incomplete and as far as I know the latest version on AUR doesn't work, so I've been recommending to use the PyPI and appimage releases since I'm personally packaging those.

**Comment by hhannine** [comment]
When did you try to install? Just checked and pillow 7 actually just yesterday on  Jul 3 became available on AUR and superpaper package has been updated and well. Did you try the 2.0.2-2 yet?

**Comment by Strykar** [comment]
Whoops, should've checked, been meaning to open this for a bit now, testing 2.0.2-2 now.

**Comment by hhannine** [comment]
How did it turn out?

**Comment by Strykar** [comment]
Weird issue, now the aur package compiles but I cannot get the Window to appear, the wallpaper changes tho, same issue with the AppImage.

**Comment by hhannine** [comment]
You can open the config window from the tray applet. Or is it not opening from there? Or are you using gnome and can't see the tray icon?

**Comment by hhannine** [comment]
If you disabled the 'show help at start' option, superpaper will run silently in the background and controllable from the tray.

**Comment by Strykar** [comment]
Just tried it in a fresh install and it works fine, closing.
