### ISSUE TITLE
Recommended way to start Superpaper on login (Gnome)

### ISSUE THREAD

**Issue by mhamrah** [hhannine/superpaper#61]
I acknowledge this is a newbie question, but what is the recommended way to start on login? I have the desktop file set as a startup application in Gnome, but it also launches the setting the settings panel. 

Thank you,

Mike

**Comment by hhannine** [comment]
Disable the 'show help at start'. That makes it open in the background.

**Comment by hhannine** [comment]
Added a tip about this to the help menu (for next release). Come message me back if you still have problems.

**Comment by mhamrah** [comment]
thank you!
