### ISSUE TITLE
Ability to pass wallpaper path to custom command

### ISSUE THREAD

**Issue by Findarato** [hhannine/superpaper#62]
I am trying to make superpaper work with https://github.com/dylanaraps/pywal but I would need the custom command to send though the wallpaper that is being set.

**Comment by hhannine** [comment]
Would you elaborate in more detail how it should work and be set up?

**Comment by esteban-diaz** [comment]
I was wondering the same... imagine I set up several wallpapers to change every 10 minutes or so... what If I want to run pywal to adopt the colour scheme of each wallpaper as they change in background, in other words.. I would like to run a custom script with every (wallpaper) change and use the wallpaper its being set at the moment (would be needing the path to the file)... is this somehow possible ? could it be made ?

**Comment by hhannine** [comment]
I think this can at least be hacked together in a separate script without changes to Superpaper.

The active wallpaper profile name is stored in the file ~/.cache/superpaper/temp/running_profile so one could monitor that and check which wallpaper files to look for. Then the temporary wallpaper image is stored in the same folder, under a name <profile_name>-a.png or  <profile_name>-b.png where the "a" and "b" alternate. The two files exist concurrently briefly while the wallpaper is being processed and applied.

If you put something working together, maybe share it here or elsewhere for others?
