### ISSUE TITLE
Readme: Please add note to restart after installation

### ISSUE THREAD

**Issue by mhbates** [hhannine/superpaper#67]
I'm fairly new to Linux, so if this is obvious, please forgive me: I spent a little time scratching my head wondering how to start this after installing. I didn't realize I needed to restart before I could run the command. After that, smooth sailing. Thanks.

**Comment by hhannine** [comment]
Added to the new documentation. Thanks for the suggestion. I've run to this once in a virtual machine and I don't know what's the cause.
