### ISSUE TITLE
unable to choose the right monitor

### ISSUE THREAD

**Issue by redteo** [hhannine/superpaper#69]
in my case i have 
a laptop with two monitor attached (hp 85690w) the nvidiadrive handle the screen like a one external monitor.
in ubuntu preferences the two actvive monitor are show like: 3 (left) 2 (right)
in superpaper i see 0 as left and 1 as right monitor..
testing all option i only get the the image compressed in each monitor...

**Comment by hhannine** [comment]
Two things:
- Superpaper just enumerates your displays from left to right (starting from 0) to have consistent numbering between all the supported platforms. If you see all your displays in the Superpaper preview, everything should be good on that part.
- The current release of Superpaper doesn't yet control the host OS wallpaper fitting style, though this has already been implemented for next release. This is why you see the image compressed on each display. To fix this on Gnome you can use the gnome tweak tool to set the wallpaper fit mode to "spanned". Or alternatively you can do it yourself by running in the terminal the following: `gsettings set org.gnome.desktop.background picture-options spanned`

**Comment by hhannine** [comment]
Did my suggestion help? I'll assume that it did and close this but if you're still having problems, come comment back, and we'll take a look.
