### ISSUE TITLE
The program does not except any of the images I try to use.  They are rejected when press 'Apply' or 'Save'

### ISSUE THREAD

**Issue by Conkersfw** [hhannine/superpaper#71]
Is there a particular type or format of image that has to be used or am I just doing something wrong?

**Comment by hhannine** [comment]
What kind of error do you get? Many common image types are supported,such as png, jpg. What type are you using?

**Comment by Conkersfw** [comment]
Hello Henri

I am using jpg.

I wondered if it was either the size of the files or the path to them was too long but I have tried making this more simple but with the same result and the program still says ‘C:\SuperPaperPics’ does not contain supported image files.”

Samuel Ward

Sent from Mail for Windows 10

**Comment by hhannine** [comment]
Thanks. This is peculiar, I've used superpaper on windows for a long time without running into this.

Can you share what type of names do the files have?

**Comment by Conkersfw** [comment]
3 examples are: -

001 Etaples WW1 Cemetary - 31-08-2019 p.JPG

034 Living Room - Waterside Cottage - 02-09-2019 p.JPG

096 Saone & Pont St Laurent - Chalon-sur-Saone - 05-09-2019 p.JPG


I have just tried making the files names simple with just 3 digit numbers but it has not made any difference.


Samuel Ward

Sent from Mail for Windows 10

**Comment by hhannine** [comment]
Thanks. Try making the file extension lower case? That might be the issue..

**Comment by Conkersfw** [comment]
Hi Henri

Success, that cured the problem. 

 Thankyou for sorting that out.  It has been driving me mad as the picture files opened in the viewing software I use, and were OK as thumbnails in file explorer, so it never occurred to me that there was a problem with the file name .

Thanks again

Samuel Ward

Sent from Mail for Windows 10

**Comment by hhannine** [comment]
Great, thanks for testing it. I've implemented a patch to fix this, will be in next release.
