### ISSUE TITLE
Autostart on Pop_OS?

### ISSUE THREAD

**Issue by mhbates** [hhannine/superpaper#72]
I saw that this doesn't run properly on Pop_OS yet, and you provided a workaround, "DESKTOP_SESSION=gnome superpaper". If the new version is still in progress, do you know of a workaround that would allow it to autostart as well? That command's not working when I set it up in Startup Applications. Thank you.

**Comment by hhannine** [comment]
Does it work if you add a delay? If not I'm not sure why.

Maybe I should think about doing a release now, or soon at least since a planned bigger feature is going to take some time.

**Comment by mhbates** [comment]
I threw it in a script and added a 5 second delay. All good now. Thank you!
