### ISSUE TITLE
Unable to select a hidden directory as a wallpaper path

### ISSUE THREAD

**Issue by vyrus714** [hhannine/superpaper#74]
I keep my wallpapers under `~/.local/share/` but the wallpaper configuration browser doesn't seem to support hidden folders. I suggest adding a check mark / toggle to show hidden files and folders. A text-box with the current selected path would also be very useful, so users can directly type out or edit the path themselves.

**Comment by hhannine** [comment]
Thanks, a toggle to show hidden items seems reasonable. I'll look into it at some point.

**Comment by AlexandreMarkus** [comment]
:+1:

**Comment by hhannine** [comment]
This has now been implemented in the file picker.
