### ISSUE TITLE
[Feature-Request] Random slideshow image on all monitors.

### ISSUE THREAD

**Issue by chiefwhosm** [hhannine/superpaper#76]
First off, can I just say this is a great piece of software. I'd been looking for something like this for a while now to allow me to use a slideshow of wallpapers on both displays without it randomly picking a different image for each screen as it has been doing under both Windows and Linux.

The way I'm doing this is via the 'separate image on each display' with the same folder of images selected for each display, and then slideshow enabled using A-Z. Unfortunately random slideshow picks independently for each display so gives the same result as Windows/Linux.

Any chance there could be a 'slideshow order' selection to randomly pick one image, and then apply it to both screens if the image chosen is also found in the other displays' image locations?

Thanks.

**Comment by hhannine** [comment]
I implemented a date seeded shuffle mode to enable your use case. If you set the exact same source folders for each display, the date seeded sort will shuffle the images the same way for each display. This was a compromise to enable what you wanted, without going all out on trying to sort out some type of image look up. Hopefully this helps. This will be out in the next release.
