### ISSUE TITLE
Set (start) profile from command line

### ISSUE THREAD

**Issue by argento-ar** [hhannine/superpaper#80]
Set a parameter on the command line for selecting the start superpaper profile.
Im using  superpaper on a notebook, when i use the notebook on the go, of course i have a single screen connected (the internal one), but when using it @ home, i use the lid closed, and two 24" monitors connected to the external ports of the laptop only.
I launch superpaper from my .xprofile file , but must adjust my "local" and "on the go" superpaper profiles manually after every launch :(

====Artix Linux (runit) , Kernel 5.9.14 , Qtile WM & picom compositor====

**Comment by hhannine** [comment]
Yes this could be a nice addition. It would need a large rework of the CLI.

For now, if you can script the way superpaper starts, you could keep superpaper running a default profile and then replace that config file in the script before you run superpaper? Or you could edit the running profile file in the temp folder, superpaper checks that at startup for the profile to resume. This file only contains the name of the profile and it's in ~/. cache/superpaper/temp or wherever your xdg cache is.

**Comment by argento-ar** [comment]
good idea hannine!, 
i think switching the default profile before launch is "cleaner" than modify de temp file, thanks for the suggestion, will work!!

**Comment by hhannine** [comment]
This has now been implemented 0702ee13f66d93295a288b9fb2e17b292270791c
