### ISSUE TITLE
GUI of app stop working on ubuntu 20.04

### ISSUE THREAD

**Issue by timothychen1999** [hhannine/superpaper#81]
Env:
OS: ubuntu 20.04.1 LTS with gnome 3.36.8
Superpaper: Superpaper-2.1.0-x86_64(Appimage)
The GUI of app stop showing up without reporting any error/exception about the gui.
Neither running the appimage or the installed version work.
I can tell the app is still running as my wallpaper slideshow set up previously occasionally change my screen.
The only major change between the last (remembered) successful run is updating driver of my graphic card (AMD 5700xt)
Log is as attached. 
[log.txt](https://github.com/hhannine/superpaper/files/5760995/log.txt)

**Comment by hhannine** [comment]
There's an error about a hotkey in the log but I'd reckon that it's unrelated, and probably just an attempt to bind a hotkey that is in use either by another Superpaper process or something else.

Did you disable the "Show help at start" option recently? This makes Superpaper run in the background and then the GUI can be accessed from the tray icon menu.

**Comment by cristobal87** [comment]
Hello,
I just installed the software and have a similar issue. I installed the software through PIP. I am pretty sure I disabled the Show help at start" which is probably the issue I got going on, however, I cant find the app in the tray menu. Is there:
a) A way to check why it doesn't show on the tray menu.
b) Modify the show help at start option from the command line?
I am also running Ubuntu 20.04 with Gnome.

cheers

**Comment by timothychen1999** [comment]
> There's an error about a hotkey in the log but I'd reckon that it's unrelated, and probably just an attempt to bind a hotkey that is in use either by another Superpaper process or something else.
> 
> Did you disable the "Show help at start" option recently? This makes Superpaper run in the background and then the GUI can be accessed from the tray icon menu.

Well, I know nothing about the option. However, I am sure that there is nothing related to superpaer in tray icons. Is there a way to check that config without accessibility to the GUI?

**Comment by cristobal87** [comment]
Thank you so much! I have done both fixes and it works like a charm now.
Your piece of software is awesome, my desktop now looks amazing!!

**Comment by hhannine** [comment]
Did my advice resolve your issue @timothychen1999, or is there still something?

**Comment by timothychen1999** [comment]
> Did my advice resolve your issue @timothychen1999, or is there still something?

Yes, it works perfectly now
