### ISSUE TITLE
An error box pops up whenever I save and restart app. Pic attached.

### ISSUE THREAD

**Issue by Horuyuki** [hhannine/superpaper#85]
**Describe the bug**
A clear and concise description of what the bug is. On Linux you can try running Superpaper in terminal with the debugging flag `-d` to see if it spits out an error, post that if it does. On Windows you can enable logging to file in the settings.

If your issue is with wallpaper spanning, check first that the OS background fitting style is set to 'span' (doesn't apply to KDE & XFCE).

**To Reproduce**

Uncheck the bind a hotkey to this profile option
Save the profile, or hit apply
A box pops up like this:
https://i.imgur.com/kTyZQTL.png
And I have to click ok 2 time to close it
Also happens at initial launch.

**Expected behavior**

Save and nothing like a box showing that error popping up since I did not check the bind a hotkey option in the first place.

**Screenshots**
If applicable, add screenshots to help explain your problem. With spanning and perspective issues a photo of your screens showing the issue in the reproduced wallpaper would be invaluable.

https://i.imgur.com/nmnmOMs.png

**Desktop (please complete the following information):**
 - OS: Arch 5.10.31, lts kernel
 - Gnome 40.0.0
 - Arch AUR with yay (when installed with paru could not launch app GUI from terminal nor with rofi, though it does change the background according to the profile I set previously before the GUI could not be started, so I just uninstalled it, cleared cache, and rebuilt with yay. Then it launched fine, I did try to reinstall it with paru but it still wouldn't start, so I switched to yay to compile.)

**Additional context**

I am very grateful for your making of this app. Was using hydra paper but it couldn't handle slide show very well since I had 2 monitors and one is vertical. This app is the only one I came up to that I can set a different source for each monitor to shuffle with. Even though I think `feh` can do it, your GUI makes it even more amazing. This way I didn't need to combine the 2 images in order for them to fit onto 2 mons as one image when configuring wall paper. Truly amazing!

Logging / debugging contents:
```
none I am afraid
```

**Comment by hhannine** [comment]
Could it be that you have more than one instance of Superpaper running?

If not, as a first remedy you can go to the general settings and clear out or modify the binding for changing the wallpaper.
It should look like this:
![image](https://user-images.githubusercontent.com/47873564/116144421-ff3eeb80-a6e4-11eb-81e3-cc46c281be03.png)

**Comment by Horuyuki** [comment]
You are right, so I went into htop to close out all other running instances. Though now that's done. for some reason I can't launch the GUI anymore, like before clicking on the app just starts a background process and changes the background. Any ideas as to why that is? Btw I am on arch linux.

**Comment by hhannine** [comment]
Once the 'show help at start' option is unchecked, superpaper starts in the background. It also should create a tray icon /applet that allows the control of the app. Though this has had some issues on gnome, something should be in the known issues in the readme.

**Comment by Horuyuki** [comment]
Is it possible to still launch the app's GUI though? I did remember unchecking the 'show help at start', so there is that.

**Comment by Horuyuki** [comment]
Please let others know you need this extension to make tray icons work in gnome.
https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
And a way to launch the config GUI regardless if 'show help at start' is checked or not.

**Comment by Horuyuki** [comment]
Umm, how do I launch the app with GUI from terminal?

**Comment by hhannine** [comment]
Thanks for the tip about the extension.

Once you have the tray applet working, the GUI is opened either by double left click on the icon, or from the right click menu (wallpaper configuration or something like that).

There is no way to force the GUI to open from the terminal. If you wish, you can re-enable the show help at start by opening the help dialog from the GUI.

**Comment by Horuyuki** [comment]
But it would be very nice if you can add a way to launch the GUI despite not having a tray. Would help a lot of people that way, since they might not know what to do after clicking the 'help' button. And I think that right clicking the try icon instead launches a new instance, do you think that is a bug?

**Comment by hhannine** [comment]
The issue is that sending commands from the terminal to a running process is a bit technical and I haven't /don't want to implement all that machinery. Maybe it would be enough to have a terminal command that ignores the help preference and opens the GUI when the process starts, I think that could be simpler enough to do. 

Maybe also a command to open the settings file in a text editor could be useful since without the tray icon one can't modify the general settings. 

Left click opens a new config window, you can have multiple open simultaneously.

**Comment by Horuyuki** [comment]
> The issue is that sending commands from the terminal to a running process is a bit technical and I haven't /don't want to implement all that machinery.
Yeah, even if it kills what is running in the background and starts a new instance, as long as there is a way to open GUI without the tray, it would be great!

**Comment by Horuyuki** [comment]
Really hope the dev can make that happen ever since gnome de-standardized the trays. What a mistake.

**Comment by Horuyuki** [comment]
Really hope the dev can make that happen ever since gnome de-standardized the trays. What a mistake.
