### ISSUE TITLE
Whole PC lagging on wallpaper change

### ISSUE THREAD

**Issue by TheAlp** [hhannine/superpaper#86]
**Describe the bug**
Whenever the program switches wallpaper (currently set to every 30 minutes) my whole PC lags for a second or two.

**To Reproduce**
Enable slideshow (currently set to shuffle if that is relevant)

**Expected behavior**
It would be preferred if changing wallpaper didn't cause a systemwide slowdown.

**Desktop (please complete the following information):**
 - OS: Windows 10 Build Version 10.0.19042 Build 19042
 - superpaper-win-installer-2.1.0.exe

Logging / debugging contents:
```
Enabled logging to file.
use_hotkeys: True
hk_binding_next: ('control', 'shift', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(2560, 1440), (1920, 1080)], OFF_ARR = [(0, 0), (2560, 0)]
Display(resolution=(2560, 1440), digital_offset=(0, 0), phys_size_mm=(597, 336), detected_phys_size_mm=(597, 336), ppi=108.91792294807368, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
Display(resolution=(1920, 1080), digital_offset=(2560, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
load_system: archive_file not found: C:\Users\Gamer\AppData\Local\Superpaper\display_systems.dat
perspective preset: default
Listed profile: 01
```

**Comment by hhannine** [comment]
Do you have perspective corrections enabled? If so, try to run a profile with perspectives disabled. Those unfortunately can be fairly taxing on the CPU and I can't do anything about that.

What kind of a CPU do you have?

**Comment by TheAlp** [comment]
I got a ryzen 5 2600x. I don't have any perspective features enabled. Using the separate image for every display feature atm.

**Comment by hhannine** [comment]
Try to disable the automatic theme color under personalization -> Colors? With that on I have stutter on my Ryzen 3900X desktop as well, and I found discussions online that people with other wallpaper software have had similar issues since Win10 1903.

This automatic theme color option:
![image](https://user-images.githubusercontent.com/47873564/119622479-dc9d1100-be0f-11eb-9c3f-5f06eb42633b.png)

**Comment by TheAlp** [comment]
Seemed to do it yeah. Hope they fix that issue in windows.
