### ISSUE TITLE
Exact display positions not preserving user input in rounding

### ISSUE THREAD

**Issue by Tom-ST** [hhannine/superpaper#89]
**Describe the bug**
When trying to set exact positions for the displays, the position that the displays are set to are not the ones I enter.
For "Top new" setting, it rounds up every 6px or 0.50mm. For example, if i put 129, 130, 131 or 132 px it will round up to 133, but if i put 128 px it will round to 127.
For "Left new" position it seems to be more random, where if i put, for example, 1160 px, it sets it to 1157 px, but for 1158 px it sets it to 1159 px.

**To Reproduce**
1. Go to 'Positions -> Exact entry'
2. Enter a new display position.
3. Apply, Save and Apply
4. Open 'Positions -> Exact entry' again.
5. See wrong values.

**Expected behavior**
Exact positions should match the values entered in the settings.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Superpaper package & version: Windows installer 2.1.0, Windows portable 2.1.0

**Log**
I first set 'Top new' to 118px, when i opened the setting again it showed as 121px. Then i set it to 116px and it showed as 115px.

> Enabled logging to file.
> use_hotkeys: True
> hk_binding_next: ('control', 'super', 'w')
> hk_binding_pause: ('control', 'super', 'shift', 'p')
> get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1080, 1920), (1920, 1080)], OFF_ARR = [(0, 0), (1080, 147)]
> Display(resolution=(1080, 1920), digital_offset=(0, 0), phys_size_mm=(270, 480), detected_phys_size_mm=(270, 480), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
> Display(resolution=(1920, 1080), digital_offset=(1080, 147), phys_size_mm=(510, 287), detected_phys_size_mm=(510, 287), ppi=95.6235294117647, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
> load_system: archive_file not found: C:\Users\Tom\Desktop\superpaper-portable\display_systems.dat
> perspective preset: default
> Listed profile: Test
> hkBinding: ('control', 'super', 'shift', 'h')
> Listed profile: example
> hkBinding: ('control', 'super', 'shift', 'g')
> Listed profile: example_multi
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> Test
> advanced
> False
> None
> None
> None
> None
> ['C:\\Users\\Tom\\Desktop\\2109.jpg']
> perspective preset: default
> Listed profile: Test
> hkBinding: ('control', 'super', 'shift', 'h')
> Listed profile: example
> hkBinding: ('control', 'super', 'shift', 'g')
> Listed profile: example_multi
> perspective preset: default
> Listed profile: Test
> hkBinding: ('control', 'super', 'shift', 'h')
> Listed profile: example
> hkBinding: ('control', 'super', 'shift', 'g')
> Listed profile: example_multi
> Unreg hotkey ('control', 'super', 'shift', 'g')
> Unreg hotkey ('control', 'super', 'shift', 'h')
> Unreg hotkey ('control', 'super', 'shift', 'p')
> Unreg hotkey ('control', 'super', 'w')
> perspective preset: default
> Listed profile: Test
> hkBinding: ('control', 'super', 'shift', 'h')
> Listed profile: example
> hkBinding: ('control', 'super', 'shift', 'g')
> Listed profile: example_multi
> Registering binding:                                 None for profile: Test
> Registering binding:                                 ('control', 'super', 'shift', 'h') for profile: example
> Registering binding:                                 ('control', 'super', 'shift', 'g') for profile: example_multi
> perspective preset: default
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> onApply profile: saved C:\Users\Tom\Desktop\superpaper-portable\profiles\Test.profile
> perspective preset: default
> perspective preset: default
> Listed profile: Test
> hkBinding: ('control', 'super', 'shift', 'h')
> Listed profile: example
> hkBinding: ('control', 'super', 'shift', 'g')
> Listed profile: example_multi
> Start profile: Test
> Check if the starting profile is already running: Test
> name check: Test, Test
> Running quick profile job with profile: Test
> quickswitch file lookup: ['Test-b.jpg']
> Starting timed profile job with profile: Test
> get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1080, 1920), (1920, 1080)], OFF_ARR = [(0, 0), (1080, 147)]
> Display(resolution=(1080, 1920), digital_offset=(0, 0), phys_size_mm=(270, 480), detected_phys_size_mm=(270, 480), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
> Display(resolution=(1920, 1080), digital_offset=(1080, 147), phys_size_mm=(510, 287), detected_phys_size_mm=(510, 287), ppi=95.6235294117647, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
> load_system: archive_file not found: C:\Users\Tom\Desktop\superpaper-portable\display_systems.dat
> running profile job with profile: Test
> Running a one-off wallpaper change.
> ['C:\\Users\\Tom\\Desktop\\2109.jpg']
> get_ppi_norm_offsets: [(0, 0), (1080, 386)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 386, 3120, 1534)]
> G_A_DSYS.use_perspective: True, prof.perspective: default
> Wrote active profile: Test
> Canvas size: [3000, 1920]
> Uncaught exception type: <class 'system_hotkey.system_hotkey.SystemRegisterError'>
> NoneType: None
> Exception: The bind could be in use elsewhere: h
> NoneType: None
> <traceback object at 0x0000021B7E389248>
> NoneType: None
> Saving DisplaySystem: key: 4280736022993132897, ppi_norm_offsets: [(0.0, 0.0), (1080.2321083172146, 386.2282398452611)], bezel_mms: [(0.0, 0.0), (0.0, 0.0)], user_diagonal_inches: None, use_perspective: True, def_perspective: None
> get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1080, 1920), (1920, 1080)], OFF_ARR = [(0, 0), (1080, 147)]
> Display(resolution=(1080, 1920), digital_offset=(0, 0), phys_size_mm=(270, 480), detected_phys_size_mm=(270, 480), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
> Display(resolution=(1920, 1080), digital_offset=(1080, 147), phys_size_mm=(510, 287), detected_phys_size_mm=(510, 287), ppi=95.6235294117647, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
> config.sections: ['4280736022993132897']
> update_bezels: (0.0, 0.0)
> update_bezels: (0.0, 0.0)
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.3124707713373, 386.2569727897519)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 386, 3120, 1534)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.0, 386.0)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 386, 3120, 1534)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.2321083172146, 386.2282398452611)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 386, 3120, 1534)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.0, 118.0)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 118, 3120, 1266)]
> Saving DisplaySystem: key: 4280736022993132897, ppi_norm_offsets: [(0.0, 0.0), (1080.2321083172146, 120.6963249516441)], bezel_mms: [(0.0, 0.0), (0.0, 0.0)], user_diagonal_inches: None, use_perspective: True, def_perspective: None
> get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1080, 1920), (1920, 1080)], OFF_ARR = [(0, 0), (1080, 147)]
> Display(resolution=(1080, 1920), digital_offset=(0, 0), phys_size_mm=(270, 480), detected_phys_size_mm=(270, 480), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
> Display(resolution=(1920, 1080), digital_offset=(1080, 147), phys_size_mm=(510, 287), detected_phys_size_mm=(510, 287), ppi=95.6235294117647, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
> config.sections: ['4280736022993132897']
> update_bezels: (0.0, 0.0)
> update_bezels: (0.0, 0.0)
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.3124707713373, 120.70530399679747)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 121, 3120, 1269)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.0, 116.0)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 116, 3120, 1264)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.0, 116.0)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 116, 3120, 1264)]
> Saving DisplaySystem: key: 4280736022993132897, ppi_norm_offsets: [(0.0, 0.0), (1080.2321083172146, 114.66150870406189)], bezel_mms: [(0.0, 0.0), (0.0, 0.0)], user_diagonal_inches: None, use_perspective: True, def_perspective: None
> get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1080, 1920), (1920, 1080)], OFF_ARR = [(0, 0), (1080, 147)]
> Display(resolution=(1080, 1920), digital_offset=(0, 0), phys_size_mm=(270, 480), detected_phys_size_mm=(270, 480), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
> Display(resolution=(1920, 1080), digital_offset=(1080, 147), phys_size_mm=(510, 287), detected_phys_size_mm=(510, 287), ppi=95.6235294117647, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
> config.sections: ['4280736022993132897']
> update_bezels: (0.0, 0.0)
> update_bezels: (0.0, 0.0)
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.3124707713373, 114.6700387969576)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 115, 3120, 1263)]
>  1534)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.0, 118.0)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 118, 3120, 1266)]
> Saving DisplaySystem: key: 4280736022993132897, ppi_norm_offsets: [(0.0, 0.0), (1080.2321083172146, 120.6963249516441)], bezel_mms: [(0.0, 0.0), (0.0, 0.0)], user_diagonal_inches: None, use_perspective: True, def_perspective: None
> get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1080, 1920), (1920, 1080)], OFF_ARR = [(0, 0), (1080, 147)]
> Display(resolution=(1080, 1920), digital_offset=(0, 0), phys_size_mm=(270, 480), detected_phys_size_mm=(270, 480), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
> Display(resolution=(1920, 1080), digital_offset=(1080, 147), phys_size_mm=(510, 287), detected_phys_size_mm=(510, 287), ppi=95.6235294117647, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
> config.sections: ['4280736022993132897']
> update_bezels: (0.0, 0.0)
> update_bezels: (0.0, 0.0)
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.3124707713373, 120.70530399679747)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 121, 3120, 1269)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.0, 116.0)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 116, 3120, 1264)]
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.0, 116.0)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 116, 3120, 1264)]
> Saving DisplaySystem: key: 4280736022993132897, ppi_norm_offsets: [(0.0, 0.0), (1080.2321083172146, 114.66150870406189)], bezel_mms: [(0.0, 0.0), (0.0, 0.0)], user_diagonal_inches: None, use_perspective: True, def_perspective: None
> get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1080, 1920), (1920, 1080)], OFF_ARR = [(0, 0), (1080, 147)]
> Display(resolution=(1080, 1920), digital_offset=(0, 0), phys_size_mm=(270, 480), detected_phys_size_mm=(270, 480), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY2')
> Display(resolution=(1920, 1080), digital_offset=(1080, 147), phys_size_mm=(510, 287), detected_phys_size_mm=(510, 287), ppi=95.6235294117647, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='\\\\.\\DISPLAY1')
> config.sections: ['4280736022993132897']
> update_bezels: (0.0, 0.0)
> update_bezels: (0.0, 0.0)
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> bezels_to_bitmap: bez_rects: ((0, 0), (0, 0))
> get_ppi_norm_offsets: [(0.0, 0.0), (1080.3124707713373, 114.6700387969576)]
> get_ppi_norm_crops: [(0, 0, 1080, 1920), (1080, 115, 3120, 1263)]

**Comment by hhannine** [comment]
This is finally now resolved by [667b604](https://github.com/hhannine/superpaper/commit/667b604f9205c3e9f0c90e1321c8b79d27070049)
