### ISSUE TITLE
[feature request] fade/crossfade transition

### ISSUE THREAD

**Issue by yogiee** [hhannine/superpaper#90]
Will it be possible to add crossfade transition between wallpaper changes? Current the change is kinda abrupt in slideshow mode, unlike Windows' own wallpaper slideshow changes.

**Comment by hhannine** [comment]
Currently Superpaper uses what the operating system provides, so at least on Windows and KDE the slideshow automatically uses a fade animation. Implementing fade on other platforms that don't do this would need a lot of work and large changes to implement it. Unless there's some simple platform specific ways to enable it, I reckon that it probably won't be done. 

What OS and Desktop are you using?

**Comment by hhannine** [comment]
This seems relevant, posting it mostly for myself to find it easily: https://stackoverflow.com/a/56974396

**Comment by yogiee** [comment]
> 
> 
> Currently Superpaper uses what the operating system provides, so at least on KDE the slideshow automatically uses a fade animation. Implementing fade on other platforms that don't do this would need a lot of work and large changes to implement it. Unless there's some simple platform specific ways to enable it, I reckon that it probably won't be done.
> 
> Edit: Whoops, somehow I missed both the fact that you said you're using Windows and that Windows is not actually doing a fade. I'll look into it at some point if it can be enabled at least on Windows.

Oh sorry, I should've mentioned that. Using Windows 10 on laptop with dual external monitors.

**Comment by hhannine** [comment]
This has now been implemented for Windows: b34c1f770e7f658d71230a86acdd2d3b112d6e8e
Out in the next release.
