### ISSUE TITLE
[Feature Request] Change wallpapers at set time or based off schedule.

### ISSUE THREAD

**Issue by GraithTiger** [hhannine/superpaper#98]
Currently the timer for slideshow changes seems to be based off the time the program starts. It would be nice if this time could instead be based of a schedule, or be able to start the slideshow at a set time. (e.g. different wallpapers for night and day)

**Comment by hhannine** [comment]
How should this work if the PC is turned off or sleeping? Timer would go off at 8 AM but the computer turns on at noon; should it change the wallpaper? I presume it should? But if it turns night time again, then I guess that it should not if the night time wallpaper is the same each night?

**Comment by hhannine** [comment]
I'm not that interested in this feature myself, and since it's a little unclear to me how this should work, I'll close this for now. If someone can come up with a clear and sensible description of the functionality, I'll look at this again.
